import type { ComponentEntry } from "../schema"

export const actionComponents = [
  {
    id: "button",
    name: "Button",
    category: "action",
    maturity: "candidate",
    summary: { ko: "현재 화면에서 동작을 실행합니다.", en: "Runs an action in the current interface." },
    whenToUse: { ko: "저장, 제출, 확인처럼 즉시 실행되는 동작에 씁니다.", en: "Use it for immediate actions such as save, submit, and confirm." },
    whenNotToUse: { ko: "다른 주소로 이동할 때는 Action이나 Text Link를 씁니다.", en: "Use Action or Text Link for navigation." },
    accessibility: { ko: "동작을 설명하는 이름을 유지하고 busy와 disabled 상태를 함께 알립니다.", en: "Keep an action-specific name and expose busy and disabled states." },
    sourcePath: "components/ui/button.tsx",
    demoKey: "button",
    importExample: 'import { Button } from "@/components/ui/button"',
    usageExample: '<Button type="submit">Save</Button>',
    relatedComponents: ["action", "button-group", "icon-control"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "실행 가능한 기본 상태와 이름을 확인합니다.", en: "Inspect the enabled default state and accessible name." } },
      { id: "hover", guidance: { ko: "색 변화가 배치를 움직이지 않는지 확인합니다.", en: "Confirm the color change does not move layout." } },
      { id: "focus-visible", guidance: { ko: "키보드 초점 표시가 선명한지 확인합니다.", en: "Confirm keyboard focus remains clearly visible." } },
      { id: "disabled", guidance: { ko: "비활성 상태에서 실행되지 않는지 확인합니다.", en: "Confirm the disabled action cannot run." } },
      { id: "loading", guidance: { ko: "이름을 유지하면서 busy 상태를 알리는지 확인합니다.", en: "Confirm busy state is exposed without replacing the label." } },
      { id: "danger", guidance: { ko: "파괴적 동작에만 Error 색을 쓰는지 확인합니다.", en: "Confirm Error color is reserved for destructive actions." } },
    ],
    props: [
      { name: "variant", type: '"primary" | "secondary" | "inverse" | "danger"', required: false, description: { ko: "동작의 위계와 의미를 정합니다.", en: "Sets action hierarchy and semantics." } },
      { name: "size", type: '"compact" | "default"', required: false, description: { ko: "컨트롤 밀도를 정합니다.", en: "Sets the control density." } },
      { name: "loading", type: "boolean", required: false, description: { ko: "중복 실행을 막고 busy 상태를 알립니다.", en: "Prevents duplicate activation and exposes busy state." } },
      { name: "type", type: '"button" | "submit" | "reset"', required: false, description: { ko: "기본값은 button입니다.", en: "Defaults to button." } },
      { name: "children", type: "ReactNode", required: true, description: { ko: "동작을 설명하는 짧은 이름입니다.", en: "A short action-specific label." } },
    ],
  },
  {
    id: "button-group",
    name: "Button Group",
    category: "action",
    maturity: "candidate",
    summary: { ko: "서로 관련된 버튼을 하나의 이름 아래 묶습니다.", en: "Groups related buttons under one accessible name." },
    whenToUse: { ko: "저장과 발행처럼 같은 맥락의 동작을 나란히 둘 때 씁니다.", en: "Use it for actions that share context, such as save and publish." },
    whenNotToUse: { ko: "서로 무관한 동작이나 긴 설명을 한 줄에 억지로 넣지 않습니다.", en: "Do not force unrelated actions or long explanations into one row." },
    accessibility: { ko: "그룹 이름으로 버튼 사이의 관계를 알리고 각 버튼 이름도 유지합니다.", en: "Name the group while preserving an action-specific name on each button." },
    sourcePath: "components/ui/button-group.tsx",
    demoKey: "button-group",
    importExample: 'import { ButtonGroup } from "@/components/ui/button-group"',
    usageExample: '<ButtonGroup label="Document actions"><Button>Save</Button><Button>Publish</Button></ButtonGroup>',
    relatedComponents: ["button"],
    dependencies: [],
    states: [
      { id: "horizontal", guidance: { ko: "인접한 버튼의 1px 선이 겹쳐 보이지 않는지 확인합니다.", en: "Check adjacent one-pixel borders read as one structure." } },
      { id: "vertical", guidance: { ko: "세로 배치에서도 그룹 이름과 조작 순서를 확인합니다.", en: "Check naming and action order in the vertical layout." } },
      { id: "wrapped", guidance: { ko: "작은 화면에서 이름을 줄이지 않고 자연스럽게 줄바꿈되는지 확인합니다.", en: "Confirm small screens wrap actions without shrinking their labels." } },
    ],
    props: [
      { name: "label", type: "string", required: true, description: { ko: "관련 동작 전체의 접근성 이름입니다.", en: "The accessible name for the related actions." } },
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, description: { ko: "동작을 배치할 방향입니다.", en: "The direction used to arrange actions." } },
      { name: "children", type: "ReactNode", required: false, description: { ko: "함께 배치할 Button입니다.", en: "The Button elements to arrange together." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
