import type { ComponentEntry } from "../schema"

export const actionComponents = [
  {
    id: "button",
    name: "Button",
    category: "action",
    maturity: "stable",
    summary: { ko: "현재 화면에서 동작을 실행합니다.", en: "Runs an action in the current interface." },
    whenToUse: { ko: "저장, 제출, 확인처럼 즉시 실행되는 동작에 씁니다.", en: "Use it for immediate actions such as save, submit, and confirm." },
    whenNotToUse: { ko: "다른 주소로 이동할 때는 Button Link나 Text Link를 씁니다.", en: "Use Button Link or Text Link for navigation." },
    accessibility: { ko: "동작을 설명하는 이름을 유지하고 busy와 disabled 상태를 함께 알립니다. 아이콘 버튼에는 aria-label이 필요합니다.", en: "Keep an action-specific name, expose busy and disabled states, and name icon buttons with aria-label." },
    sourcePath: "components/ui/button.tsx",
    demoKey: "button",
    importExample: 'import { Button } from "@/components/ui/button"',
    usageExample: '<Button type="submit">Save</Button>',
    relatedComponents: ["button-link", "button-group"],
    dependencies: [],
    states: [
      { id: "primary", guidance: { ko: "한 화면의 가장 중요한 동작에만 파란 면을 씁니다.", en: "Reserve the blue surface for the most important action in a view." } },
      { id: "secondary", guidance: { ko: "보조 동작은 Paper 면과 1px 선으로 표시합니다.", en: "Render secondary actions with a Paper surface and one-pixel rule." } },
      { id: "inverse", guidance: { ko: "어두운 면 위에서 경계와 이름이 선명한지 확인합니다.", en: "Confirm the boundary and label remain clear on dark surfaces." } },
      { id: "ghost", guidance: { ko: "시각적 무게가 낮아도 조작 영역과 초점 표시는 유지합니다.", en: "Keep the target and focus indicator even at low visual emphasis." } },
      { id: "icon", guidance: { ko: "아이콘만 보일 때 접근성 이름과 모바일 44px 조작 영역을 확인합니다.", en: "For icon-only controls, verify the accessible name and 44px mobile target." } },
      { id: "disabled", guidance: { ko: "비활성 상태에서 실행되지 않는지 확인합니다.", en: "Confirm the disabled action cannot run." } },
      { id: "loading", guidance: { ko: "이름을 유지하면서 busy 상태를 알리는지 확인합니다.", en: "Confirm busy state is exposed without replacing the label." } },
      { id: "danger", guidance: { ko: "파괴적 동작에만 Error Deep과 흰색 전경을 씁니다.", en: "Use Error Deep with a white foreground only for destructive actions." } },
    ],
    props: [
      { name: "variant", type: '"primary" | "secondary" | "inverse" | "danger" | "ghost"', required: false, description: { ko: "동작의 위계와 의미를 정합니다.", en: "Sets action hierarchy and semantics." } },
      { name: "size", type: '"compact" | "default" | "icon"', required: false, description: { ko: "컨트롤 밀도와 아이콘 전용 크기를 정합니다.", en: "Sets control density, including the icon-only size." } },
      { name: "loading", type: "boolean", required: false, description: { ko: "중복 실행을 막고 busy 상태를 알립니다.", en: "Prevents duplicate activation and exposes busy state." } },
      { name: "type", type: '"button" | "submit" | "reset"', required: false, description: { ko: "기본값은 button입니다.", en: "Defaults to button." } },
      { name: "children", type: "ReactNode", required: true, description: { ko: "동작 이름 또는 아이콘입니다.", en: "The action label or icon." } },
    ],
  },
  {
    id: "button-link",
    name: "Button Link",
    category: "action",
    maturity: "stable",
    summary: { ko: "Button과 같은 모양을 쓰되 native anchor로 다른 주소에 이동합니다.", en: "Uses Button's appearance while preserving a native anchor for navigation." },
    whenToUse: { ko: "강한 CTA가 페이지나 주소 이동일 때만 씁니다.", en: "Use it only when a prominent CTA navigates to another page or address." },
    whenNotToUse: { ko: "저장, 제출, 모달 열기처럼 현재 화면에서 실행되는 동작에는 Button을 씁니다.", en: "Use Button for in-place actions such as save, submit, or opening a dialog." },
    accessibility: { ko: "Button으로 대체하지 말고 native anchor 의미와 목적지가 드러나는 이름을 유지합니다.", en: "Do not replace it with Button; preserve native anchor semantics and a destination-specific name." },
    sourcePath: "components/ui/button-link.tsx",
    demoKey: "button-link",
    importExample: 'import { ButtonLink } from "@/components/ui/button-link"',
    usageExample: '<ButtonLink href="/design">Design guide</ButtonLink>',
    relatedComponents: ["button", "text-link"],
    dependencies: [],
    states: [
      { id: "primary", guidance: { ko: "주요 이동 목적지를 파란 면으로 표시합니다.", en: "Present the primary destination on a blue surface." } },
      { id: "secondary", guidance: { ko: "보조 이동은 Paper 면과 1px 선으로 표시합니다.", en: "Present supporting navigation with Paper and a one-pixel rule." } },
      { id: "inverse", guidance: { ko: "어두운 면에서도 링크 목적지가 선명한지 확인합니다.", en: "Confirm the destination remains clear on dark surfaces." } },
      { id: "ghost", guidance: { ko: "낮은 위계의 이동에도 링크 초점 표시를 유지합니다.", en: "Keep link focus visible at low hierarchy." } },
      { id: "icon", guidance: { ko: "아이콘 링크에는 목적지를 설명하는 aria-label이 필요합니다.", en: "Icon links require an aria-label that names the destination." } },
    ],
    props: [
      { name: "href", type: "string", required: true, description: { ko: "이동할 주소입니다.", en: "The navigation destination." } },
      { name: "variant", type: '"primary" | "secondary" | "inverse" | "danger" | "ghost"', required: false, description: { ko: "링크의 시각 위계를 정합니다.", en: "Sets the link's visual hierarchy." } },
      { name: "size", type: '"compact" | "default" | "icon"', required: false, description: { ko: "컨트롤 밀도를 정합니다.", en: "Sets the control density." } },
      { name: "children", type: "ReactNode", required: true, description: { ko: "목적지를 설명하는 이름 또는 아이콘입니다.", en: "The destination label or icon." } },
    ],
  },
  {
    id: "button-group",
    name: "Button Group",
    category: "action",
    maturity: "candidate",
    summary: { ko: "관련 동작과 보조 요소를 하나의 연결된 틀로 묶습니다.", en: "Composes related actions and supporting parts in one connected frame." },
    whenToUse: { ko: "저장과 발행, 분할 동작, 입력과 실행처럼 같은 맥락의 요소를 묶을 때 씁니다.", en: "Use it for related actions, split actions, or an input paired with its action." },
    whenNotToUse: { ko: "서로 무관한 동작이나 긴 설명을 한 줄에 억지로 넣지 않습니다.", en: "Do not force unrelated actions or long explanations into one row." },
    accessibility: { ko: "그룹 이름으로 관계를 알리고 각 컨트롤의 고유 이름도 유지합니다.", en: "Name the group while preserving a specific name for every control." },
    sourcePath: "components/ui/button-group.tsx",
    demoKey: "button-group",
    importExample: 'import { ButtonGroup, ButtonGroupSeparator, ButtonGroupText } from "@/components/ui/button-group"',
    usageExample: '<ButtonGroup label="Document actions"><Button>Save</Button><ButtonGroupSeparator /><Button>Publish</Button></ButtonGroup>',
    relatedComponents: ["button", "button-link", "dropdown-menu", "input-group"],
    dependencies: [],
    states: [
      { id: "horizontal", guidance: { ko: "인접 요소의 1px 선이 하나의 구조로 읽히는지 확인합니다.", en: "Check adjacent one-pixel borders read as one structure." } },
      { id: "vertical", guidance: { ko: "세로 배치에서도 이름과 조작 순서를 확인합니다.", en: "Check naming and action order in the vertical layout." } },
      { id: "split", guidance: { ko: "주요 동작과 옵션 메뉴의 경계와 이름을 확인합니다.", en: "Inspect the boundary and names of the main action and options menu." } },
      { id: "input", guidance: { ko: "입력과 실행 버튼이 하나의 필드처럼 연결되는지 확인합니다.", en: "Confirm the input and action read as one composed field." } },
    ],
    props: [
      { name: "label", type: "string", required: false, description: { ko: "관련 요소 전체의 접근성 이름입니다.", en: "The accessible name for the related controls." } },
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, description: { ko: "요소를 배치할 방향입니다.", en: "The direction used to arrange controls." } },
      { name: "children", type: "ReactNode", required: true, description: { ko: "Button, 입력, 텍스트, 구분선 등 함께 배치할 요소입니다.", en: "Buttons, inputs, text, separators, or nested groups to compose." } },
    ],
  },
  {
    id: "segmented-control",
    name: "Segmented Control",
    category: "selection",
    maturity: "candidate",
    summary: { ko: "둘 이상의 짧은 선택지 중 하나를 고릅니다.", en: "Selects one value from two or more short options." },
    whenToUse: { ko: "언어, 보기 방식, 상태처럼 같은 수준의 짧은 값을 즉시 전환할 때 씁니다.", en: "Use it to switch short peer values such as locale, view, or status." },
    whenNotToUse: { ko: "긴 설명이 필요하거나 선택지가 많으면 Radio Group이나 Select를 씁니다.", en: "Use Radio Group or Select for verbose or numerous options." },
    accessibility: { ko: "radiogroup과 radio 의미, aria-checked, 방향키 로빙 초점을 제공합니다.", en: "Provides radiogroup and radio semantics, aria-checked, and arrow-key roving focus." },
    sourcePath: "components/ui/segmented-control.tsx",
    demoKey: "segmented-control",
    importExample: 'import { SegmentedControl } from "@/components/ui/segmented-control"',
    usageExample: '<SegmentedControl label="View" value={view} options={options} onValueChange={setView} />',
    relatedComponents: ["radio-group", "tabs"],
    dependencies: ["motion"],
    states: [
      { id: "default", guidance: { ko: "이름 있는 그룹과 모든 선택지가 한 구조로 읽히는지 확인합니다.", en: "Confirm the named group and all options read as one control." } },
      { id: "three-options", guidance: { ko: "폭이 다른 세 선택지에서도 선택 면이 정확히 맞는지 확인합니다.", en: "Confirm the selected surface fits three unequal labels." } },
      { id: "focus-visible", guidance: { ko: "방향키가 다음 활성 선택지로 초점과 값을 함께 옮기는지 확인합니다.", en: "Confirm arrow keys move focus and value to the next enabled option." } },
      { id: "selected", guidance: { ko: "선택 면과 aria-checked가 함께 바뀌는지 확인합니다.", en: "Confirm the selected surface and aria-checked change together." } },
      { id: "disabled", guidance: { ko: "비활성 선택지를 클릭과 방향키가 건너뛰는지 확인합니다.", en: "Confirm pointer and keyboard navigation skip disabled options." } },
      { id: "reduced-motion", guidance: { ko: "동작 줄이기에서도 선택 상태는 즉시 분명해야 합니다.", en: "Keep selection immediately clear under reduced motion." } },
    ],
    props: [
      { name: "label", type: "string", required: true, description: { ko: "선택지 그룹의 접근성 이름입니다.", en: "The accessible name for the option group." } },
      { name: "value", type: "Value", required: true, description: { ko: "현재 선택한 값입니다.", en: "The currently selected value." } },
      { name: "options", type: "readonly SegmentedControlOption<Value>[]", required: true, description: { ko: "값, 이름, 화면 내용, 비활성 상태를 담은 둘 이상의 선택지입니다.", en: "Two or more options with values, labels, content, and optional disabled state." } },
      { name: "onValueChange", type: "(value: Value) => void", required: true, description: { ko: "선택값이 바뀔 때 호출합니다.", en: "Called when the selected value changes." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
