import type { ComponentEntry } from "../schema"

export const coreUiC3CComponents = [
  {
    id: "dialog",
    name: "Dialog",
    category: "overlay",
    maturity: "candidate",
    summary: { ko: "현재 흐름 위에서 집중이 필요한 짧은 작업을 엽니다.", en: "Opens a focused, short task above the current flow." },
    whenToUse: { ko: "설정이나 짧은 폼을 현재 맥락 안에서 처리할 때 씁니다.", en: "Use it for settings or a short form without leaving context." },
    whenNotToUse: { ko: "긴 문서나 되돌리기 어려운 결정에는 쓰지 않습니다.", en: "Do not use it for long documents or consequential decisions." },
    accessibility: { ko: "제목과 설명, 초점 가두기, Escape 닫기와 트리거 초점 복귀를 유지합니다.", en: "Preserves naming, focus trapping, Escape dismissal, and trigger focus restoration." },
    sourcePath: "components/ui/dialog.tsx",
    demoKey: "dialog",
    importExample: 'import { Dialog, DialogTrigger, DialogContent, DialogBody, DialogFooter, DialogClose } from "@/components/ui/dialog"',
    usageExample: '<Dialog><DialogTrigger>Settings</DialogTrigger><DialogContent size="medium" scroll="body"><DialogBody>...</DialogBody><DialogFooter><DialogClose>Done</DialogClose></DialogFooter></DialogContent></Dialog>',
    relatedComponents: ["alert-dialog", "button", "field"],
    dependencies: ["@phosphor-icons/react", "radix-ui"],
    states: [
      { id: "closed", guidance: { ko: "트리거가 열릴 작업을 구체적으로 설명하는지 확인합니다.", en: "Confirm the trigger names the task it opens." } },
      { id: "open", guidance: { ko: "제목, 본문, 동작과 닫기 경계가 분명한지 확인합니다.", en: "Inspect the title, body, actions, and close boundary." } },
      { id: "body-scroll", guidance: { ko: "긴 본문만 스크롤되고 제목과 동작은 접근 가능한지 확인합니다.", en: "Confirm only the long body scrolls while title and actions remain reachable." } },
    ],
    props: [
      { name: "size", type: '"small" | "medium" | "large" | "full"', required: false, description: { ko: "작업에 맞는 대화상자 너비입니다.", en: "Sets the dialog width for the task." } },
      { name: "scroll", type: '"content" | "body"', required: false, description: { ko: "전체 또는 DialogBody의 스크롤 경계입니다.", en: "Chooses the content or DialogBody scrolling boundary." } },
      { name: "closeLabel", type: "string", required: false, description: { ko: "호환용 닫기 아이콘을 추가합니다. 새 작업은 DialogClose를 조합합니다.", en: "Adds the compatibility close icon; new work composes DialogClose." } },
    ],
  },
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    category: "overlay",
    maturity: "candidate",
    summary: { ko: "되돌리기 어려운 행동 전에 명시적인 결정을 받습니다.", en: "Requests an explicit decision before a consequential action." },
    whenToUse: { ko: "삭제나 권한 변경처럼 결과가 즉시 적용되는 행동에 씁니다.", en: "Use it for immediate actions such as deletion or permission changes." },
    whenNotToUse: { ko: "일반 안내나 쉽게 되돌릴 수 있는 행동에는 Dialog나 Alert를 씁니다.", en: "Use Dialog or Alert for general information or reversible actions." },
    accessibility: { ko: "바깥 클릭으로 닫지 않고 취소와 실행을 명확히 제공하며 초점을 복귀합니다.", en: "Requires cancel or action, ignores outside dismissal, and restores focus." },
    sourcePath: "components/ui/alert-dialog.tsx",
    demoKey: "alert-dialog",
    importExample: 'import { AlertDialog, AlertDialogContent, AlertDialogBody, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog"',
    usageExample: '<AlertDialog><AlertDialogContent><AlertDialogBody>This cannot be undone.</AlertDialogBody><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive">Archive</AlertDialogAction></AlertDialogContent></AlertDialog>',
    relatedComponents: ["dialog", "alert", "button"],
    dependencies: ["radix-ui"],
    states: [
      { id: "closed", guidance: { ko: "트리거가 결과를 구체적으로 설명하는지 확인합니다.", en: "Confirm the trigger names the consequence." } },
      { id: "open", guidance: { ko: "취소와 실행의 위계, 초기 초점과 초점 복귀를 확인합니다.", en: "Inspect action hierarchy, initial focus, and focus restoration." } },
      { id: "destructive", guidance: { ko: "위험 동작은 Error Deep 면과 흰색 글자를 사용합니다.", en: "Use the Error Deep surface and white text for a destructive action." } },
    ],
    props: [
      { name: "variant", type: '"primary" | "destructive"', required: false, description: { ko: "확인 동작의 의미입니다.", en: "Sets the confirmation action intent." } },
      { name: "children", type: "ReactNode", required: false, description: { ko: "Header, Body와 Footer를 조합합니다.", en: "Composes Header, Body, and Footer." } },
    ],
  },
  {
    id: "pagination",
    name: "Pagination",
    category: "navigation",
    maturity: "candidate",
    summary: { ko: "연결된 레일에서 컬렉션의 이전, 다음, 특정 페이지로 이동합니다.", en: "Navigates a collection from one connected page rail." },
    whenToUse: { ko: "목록이 URL로 구분된 여러 페이지를 가질 때 씁니다.", en: "Use it when a collection has multiple URL-addressable pages." },
    whenNotToUse: { ko: "슬라이드나 현재 화면 안의 탭 전환에는 쓰지 않습니다.", en: "Do not use it for slides or in-page tabs." },
    accessibility: { ko: "이름 있는 nav, 실제 링크, aria-current와 비활성 경계를 제공합니다.", en: "Uses a named nav, real links, aria-current, and disabled boundaries." },
    sourcePath: "components/ui/pagination.tsx",
    demoKey: "pagination",
    importExample: 'import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationPrevious, PaginationNext } from "@/components/ui/pagination"',
    usageExample: '<Pagination aria-label="Document pages"><PaginationContent><PaginationItem><PaginationLink href="?page=2" isCurrent>2</PaginationLink></PaginationItem></PaginationContent></Pagination>',
    relatedComponents: ["data-table", "breadcrumb", "text-link"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "default", guidance: { ko: "이전과 다음이 실제 목적지 링크인지 확인합니다.", en: "Confirm previous and next are real destination links." } },
      { id: "current", guidance: { ko: "현재 페이지가 aria-current와 파란 면으로 전달되는지 확인합니다.", en: "Confirm the current page uses aria-current and the blue surface." } },
      { id: "boundary", guidance: { ko: "첫 페이지와 마지막 페이지의 비활성 방향이 목적지를 노출하지 않는지 확인합니다.", en: "Confirm disabled boundary directions expose no destination." } },
      { id: "collapsed", guidance: { ko: "긴 범위는 축약하되 현재 위치는 유지합니다.", en: "Collapse long ranges while preserving the current position." } },
    ],
    props: [
      { name: "isCurrent", type: "boolean", required: false, description: { ko: "현재 페이지 링크를 표시합니다.", en: "Marks the current page link." } },
      { name: "disabled", type: "boolean", required: false, description: { ko: "방향 경계를 보이되 이동은 막습니다.", en: "Keeps a boundary visible without navigation." } },
      { name: "label", type: "string", required: true, description: { ko: "방향이나 축약 표시의 접근 가능한 이름입니다.", en: "Names a direction or ellipsis accessibly." } },
    ],
  },
  {
    id: "spinner",
    name: "Spinner",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "고정된 사각 테두리를 따라 열린 구간이 흐르며 완료 시점을 알 수 없는 진행을 알립니다.", en: "Signals indeterminate progress as one gap travels around a stationary square perimeter." },
    whenToUse: { ko: "버튼이나 짧은 인라인 작업에서 잠시 기다릴 때 씁니다.", en: "Use it inside a button or compact inline task." },
    whenNotToUse: { ko: "진행률을 알 수 있거나 넓은 페이지 로딩에는 Progress나 Skeleton을 씁니다.", en: "Use Progress for measurable work and Skeleton for page loading." },
    accessibility: { ko: "이름 있는 status를 제공하고 하나의 사각 궤적은 장식으로 숨깁니다.", en: "Provides a named status and hides the stationary square track as presentation." },
    sourcePath: "components/ui/spinner.tsx",
    demoKey: "spinner",
    importExample: 'import { Spinner } from "@/components/ui/spinner"',
    usageExample: '<Spinner label="Saving document" size="compact" />',
    relatedComponents: ["button", "progress", "skeleton"],
    dependencies: [],
    states: [
      { id: "compact", guidance: { ko: "버튼 안에서도 작업 이름이 구체적인지 확인합니다.", en: "Confirm the task name remains specific inside a button." } },
      { id: "default", guidance: { ko: "사각형은 고정된 채 열린 구간만 테두리를 따라 흐르는지 확인합니다.", en: "Confirm the square remains fixed while its gap travels around the perimeter." } },
      { id: "reduced-motion", guidance: { ko: "움직임 없이도 하나의 열린 변으로 대기 상태가 보이는지 확인합니다.", en: "Confirm one quiet gap communicates pending state without motion." } },
    ],
    props: [
      { name: "label", type: "string", required: true, description: { ko: "진행 중인 작업의 접근 가능한 이름입니다.", en: "Names the pending task." } },
      { name: "size", type: '"compact" | "default" | "large"', required: false, description: { ko: "사각 표시 크기입니다.", en: "Sets the square indicator size." } },
    ],
  },
  {
    id: "toast",
    name: "Toast",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "현재 작업을 막지 않고 짧은 결과를 전역 큐로 알립니다.", en: "Reports a brief result through one application-wide queue." },
    whenToUse: { ko: "저장, 업로드, 되돌리기처럼 짧은 결과와 선택 동작에 씁니다.", en: "Use it for brief save, upload, or undo outcomes." },
    whenNotToUse: { ko: "지속되는 오류나 반드시 결정해야 하는 내용에는 Alert나 Alert Dialog를 씁니다.", en: "Use Alert or Alert Dialog for persistent errors or required decisions." },
    accessibility: { ko: "일반 결과는 status, 오류는 alert로 알리고 번역된 닫기 이름을 제공합니다.", en: "Announces routine results as status, errors as alert, and localizes dismissal." },
    sourcePath: "components/ui/toast.tsx",
    demoKey: "toast",
    importExample: 'import { ToastProvider, useToast } from "@/components/ui/toast"',
    usageExample: 'const toast = useToast(); toast.success("Saved", { description: "Changes are live." })',
    relatedComponents: ["alert", "status-label", "spinner"],
    dependencies: ["radix-ui"],
    states: [
      { id: "success", guidance: { ko: "완료 결과를 한 문장으로 설명합니다.", en: "Describe the completed outcome in one sentence." } },
      { id: "error", guidance: { ko: "오류는 더 오래 표시하고 복구 설명은 짧게 유지합니다.", en: "Keep errors visible longer and recovery copy concise." } },
      { id: "action", guidance: { ko: "되돌리기 같은 한 가지 보조 동작만 제공합니다.", en: "Offer one supporting action such as Undo." } },
      { id: "queued", guidance: { ko: "세 개를 넘는 알림은 앞선 알림이 닫힐 때까지 대기합니다.", en: "Queue notifications beyond the three visible items." } },
      { id: "persistent", guidance: { ko: "duration 0은 사용자가 직접 닫을 때까지 유지합니다.", en: "Use duration zero only for deliberate persistence." } },
    ],
    props: [
      { name: "show", type: "(options: ToastOptions) => string", required: true, description: { ko: "알림을 표시하거나 같은 ID를 갱신합니다.", en: "Shows a toast or updates a matching stable ID." } },
      { name: "duration", type: "number", required: false, description: { ko: "자동 닫기 시간이며 0이면 유지됩니다.", en: "Sets auto-dismiss time; zero persists." } },
      { name: "tone", type: '"neutral" | "info" | "success" | "warning" | "error"', required: false, description: { ko: "알림 결과의 의미입니다.", en: "Sets the result tone." } },
      { name: "action", type: "{ label: string; onClick: () => void }", required: false, description: { ko: "한 가지 선택 동작입니다.", en: "Provides one optional action." } },
    ],
  },
  {
    id: "alert",
    name: "Alert",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "본문 흐름 안에 계속 남아 있는 상태와 다음 행동을 설명합니다.", en: "Explains a persistent inline state and its next action." },
    whenToUse: { ko: "정보, 성공, 주의, 오류가 다음 작업과 함께 남아야 할 때 씁니다.", en: "Use it when information, success, warning, or error must remain with the task." },
    whenNotToUse: { ko: "짧게 끝난 결과나 명시적 결정에는 Toast나 Alert Dialog를 씁니다.", en: "Use Toast for brief outcomes and Alert Dialog for decisions." },
    accessibility: { ko: "보이는 제목으로 영역을 이름 붙이고 새 긴급 오류에만 live를 사용합니다.", en: "Labels the region from a visible title and reserves live for new urgent errors." },
    sourcePath: "components/ui/alert.tsx",
    demoKey: "alert",
    importExample: 'import { Alert, AlertIcon, AlertContent, AlertTitle, AlertDescription, AlertAction } from "@/components/ui/alert"',
    usageExample: '<Alert variant="error"><AlertContent><AlertTitle>Save failed</AlertTitle><AlertDescription>Review the title.</AlertDescription></AlertContent><AlertAction>Retry</AlertAction></Alert>',
    relatedComponents: ["toast", "alert-dialog", "button"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "info", guidance: { ko: "왼쪽 상태 신호와 제목으로 정보를 구분합니다.", en: "Distinguish information with the left status signal and title." } },
      { id: "warning", guidance: { ko: "주의 상태와 다음 행동을 구체적으로 적습니다.", en: "State the caution and next action concretely." } },
      { id: "error", guidance: { ko: "오류 원인과 가능한 복구 동작을 함께 제공합니다.", en: "Provide the error reason and an available recovery action." } },
      { id: "live", guidance: { ko: "새 긴급 상태만 alert로 발표합니다.", en: "Announce only a newly created urgent state as an alert." } },
    ],
    props: [
      { name: "title", type: "ReactNode", required: false, description: { ko: "기존 사용법을 위한 단축 제목입니다.", en: "Compatibility shorthand for a visible title." } },
      { name: "variant", type: '"info" | "success" | "warning" | "error"', required: false, description: { ko: "상태의 의미입니다.", en: "Sets the feedback meaning." } },
      { name: "live", type: "boolean", required: false, description: { ko: "새 긴급 상태를 즉시 발표합니다.", en: "Announces a newly rendered urgent state." } },
    ],
  },
  {
    id: "status-label",
    name: "Status Label",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "작은 색상 사각형과 짧은 텍스트로 실제 개체 상태를 나타냅니다.", en: "Shows a real entity state with a small color square and concise text." },
    whenToUse: { ko: "문서나 미디어의 발행·처리 상태처럼 정적인 메타데이터에 씁니다.", en: "Use it for static document or media lifecycle metadata." },
    whenNotToUse: { ko: "클릭 동작, 필터, 긴 설명이나 실시간 오류를 대신하지 않습니다.", en: "Do not use it as an action, filter, long explanation, or live error." },
    accessibility: { ko: "색이 없어도 뜻이 분명한 텍스트를 반드시 제공합니다.", en: "Always provide explicit status text that remains clear without color." },
    sourcePath: "components/ui/status-label.tsx",
    demoKey: "status-label",
    importExample: 'import { StatusLabel } from "@/components/ui/status-label"',
    usageExample: '<StatusLabel tone="success">Published</StatusLabel>',
    relatedComponents: ["alert", "panel", "toast"],
    dependencies: [],
    states: [
      { id: "neutral", guidance: { ko: "초안 같은 중립 상태를 짧은 문구로 표시합니다.", en: "Describe a neutral state such as Draft concisely." } },
      { id: "info", guidance: { ko: "처리 중 상태를 정보 문구와 함께 표시합니다.", en: "Pair an in-progress state with explicit text." } },
      { id: "success", guidance: { ko: "완료 상태를 구체적인 텍스트로 표시합니다.", en: "Name the completed state explicitly." } },
      { id: "warning", guidance: { ko: "확인이 필요한 상태를 문구로 설명합니다.", en: "Explain what state requires review." } },
      { id: "error", guidance: { ko: "실패 상태를 오류 원인과 혼동하지 않게 짧게 표시합니다.", en: "Label the failed state without replacing the error explanation." } },
    ],
    props: [
      { name: "tone", type: '"neutral" | "info" | "success" | "warning" | "error"', required: false, description: { ko: "상태 사각형의 의미 색상입니다.", en: "Sets the semantic color of the status square." } },
      { name: "variant", type: '"neutral" | "info" | "success" | "warning" | "error"', required: false, description: { ko: "한 번의 호환 기간 동안 유지되는 별칭입니다.", en: "Compatibility alias retained for one release." } },
      { name: "children", type: "ReactNode", required: true, description: { ko: "상태를 직접 설명하는 짧은 문구입니다.", en: "Concise text that names the state." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
