import type { ComponentEntry } from "../schema"

export const coreExpansionC2Components = [
  {
    id: "table",
    name: "Table",
    category: "content",
    maturity: "candidate",
    summary: { ko: "열과 행으로 비교해야 하는 정보를 native table로 보여줍니다.", en: "Presents information that must be compared across native table rows and columns." },
    whenToUse: { ko: "상태, 이름, 날짜처럼 같은 속성을 여러 항목에서 비교할 때 씁니다.", en: "Use it to compare the same attributes, such as status, name, or date, across records." },
    whenNotToUse: { ko: "한 항목의 상세 정보나 작은 화면에서 순서만 중요한 목록에는 Item을 씁니다.", en: "Use Item for one record's details or a list whose sequence matters more than column comparison." },
    accessibility: { ko: "caption, thead, tbody, th scope 등 native 표 구조를 유지합니다.", en: "Preserves native caption, thead, tbody, and scoped header semantics." },
    sourcePath: "components/ui/table.tsx",
    demoKey: "table",
    importExample: 'import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"',
    usageExample: '<Table aria-label="Deployments"><TableHeader><TableRow><TableHead>Service</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Laf ID</TableCell></TableRow></TableBody></Table>',
    relatedComponents: ["data-table", "item", "separator"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "열 제목과 행의 대응 관계가 빠르게 읽히는지 확인합니다.", en: "Confirm column headers and row values scan as one relationship." } },
      { id: "overflow", guidance: { ko: "작은 화면에서 표 의미를 유지한 채 가로 스크롤되는지 확인합니다.", en: "Confirm small screens scroll horizontally without breaking table semantics." } },
    ],
    props: [
      { name: "aria-label", type: "string", required: false, description: { ko: "보이는 caption이 없을 때 표의 이름을 제공합니다.", en: "Names the table when no visible caption is present." } },
      { name: "align", type: '"start" | "center" | "end"', required: false, description: { ko: "열 제목과 셀 내용의 정렬입니다.", en: "Aligns header and cell content." } },
      { name: "scope", type: "string", required: false, description: { ko: "TableHead가 설명하는 행이나 열 범위입니다.", en: "The row or column scope described by TableHead." } },
    ],
  },
  {
    id: "data-table",
    name: "Data Table",
    category: "content",
    maturity: "candidate",
    summary: { ko: "정렬과 빈 상태가 필요한 구조화 데이터를 보여줍니다.", en: "Displays structured data with sorting and an explicit empty state." },
    whenToUse: { ko: "관리 목록처럼 사용자가 열 기준으로 데이터를 다시 정렬해야 할 때 씁니다.", en: "Use it for operational lists that people need to reorder by column." },
    whenNotToUse: { ko: "정적 비교에는 Table을, 카드형 탐색에는 Item을 씁니다.", en: "Use Table for static comparison and Item for editorial browsing." },
    accessibility: { ko: "정렬 버튼과 aria-sort를 연결하고 실제 Table 구조를 유지합니다.", en: "Connects sort buttons with aria-sort while preserving real Table semantics." },
    sourcePath: "components/ui/data-table.tsx",
    demoKey: "data-table",
    importExample: 'import { DataTable, type DataTableColumn } from "@/components/ui/data-table"',
    usageExample: '<DataTable aria-label="Services" columns={columns} rows={rows} getRowKey={(row) => row.id} emptyText="No services" />',
    relatedComponents: ["table", "pagination", "empty-state"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "default", guidance: { ko: "정렬 가능한 열과 정적 열을 구분합니다.", en: "Distinguish sortable columns from static columns." } },
      { id: "sorted", guidance: { ko: "현재 정렬 열과 방향이 아이콘과 접근성 트리에 함께 나타나는지 확인합니다.", en: "Confirm the active column and direction appear visually and in the accessibility tree." } },
      { id: "empty", guidance: { ko: "빈 상태가 모든 열을 가로질러 짧게 설명되는지 확인합니다.", en: "Confirm the empty state spans the table with concise copy." } },
    ],
    props: [
      { name: "columns", type: "readonly DataTableColumn<Row>[]", required: true, description: { ko: "셀 렌더링과 선택적 정렬값을 정의합니다.", en: "Defines cell rendering and optional sort values." } },
      { name: "rows", type: "readonly Row[]", required: true, description: { ko: "표에 표시할 실제 데이터입니다.", en: "The real records displayed by the table." } },
      { name: "getRowKey", type: "(row: Row) => string", required: true, description: { ko: "각 행의 안정적인 식별자를 반환합니다.", en: "Returns a stable identifier for each row." } },
      { name: "emptyText", type: "string", required: true, description: { ko: "표시할 행이 없을 때의 안내입니다.", en: "Copy shown when there are no rows." } },
    ],
  },
  {
    id: "item",
    name: "Item",
    category: "structure",
    maturity: "candidate",
    summary: { ko: "미디어, 본문, 메타데이터와 동작을 하나의 행으로 구성합니다.", en: "Composes media, copy, metadata, and actions into one row." },
    whenToUse: { ko: "저장소, 문서, 사람처럼 반복되는 개체를 카드 없이 나열할 때 씁니다.", en: "Use it for repeated entities such as repositories, documents, or people without card grids." },
    whenNotToUse: { ko: "열 비교가 핵심이면 Table을, 독립된 영역이면 Panel을 씁니다.", en: "Use Table for column comparison and Panel for a standalone region." },
    accessibility: { ko: "주변 목록에 맞는 article, div, li 요소를 선택하고 제목으로 이름을 연결합니다.", en: "Chooses article, div, or li for the surrounding structure and labels the item from its title." },
    sourcePath: "components/ui/item.tsx",
    demoKey: "item",
    importExample: 'import { Item, ItemMedia, ItemContent, ItemTitle, ItemDescription, ItemActions } from "@/components/ui/item"',
    usageExample: '<Item as="li"><ItemMedia>LF</ItemMedia><ItemContent><ItemTitle>lafetch</ItemTitle><ItemDescription>Typed fetch utilities.</ItemDescription></ItemContent><ItemActions>Open</ItemActions></Item>',
    relatedComponents: ["panel", "table", "status-label"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "제목, 설명, 메타데이터와 동작의 읽기 순서를 확인합니다.", en: "Inspect the reading order of title, description, metadata, and actions." } },
      { id: "subtle", guidance: { ko: "조용한 면이 인접 행 경계보다 강해지지 않는지 확인합니다.", en: "Confirm the quiet surface does not overpower adjacent row structure." } },
      { id: "inverse", guidance: { ko: "Ink 면에서 본문과 보조 문구 대비를 확인합니다.", en: "Verify primary and supporting copy contrast on the Ink surface." } },
    ],
    props: [
      { name: "as", type: '"article" | "div" | "li"', required: false, description: { ko: "주변 문서 구조에 맞는 HTML 요소입니다.", en: "The HTML element that fits the surrounding document structure." } },
      { name: "tone", type: '"default" | "subtle" | "inverse"', required: false, description: { ko: "행의 표면 대비입니다.", en: "The surface contrast of the row." } },
    ],
  },
  {
    id: "progress",
    name: "Progress",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "측정 가능한 작업의 진행률이나 연결 중 상태를 보여줍니다.", en: "Shows measurable completion or an indeterminate connection state." },
    whenToUse: { ko: "업로드, 처리, 동기화처럼 시간이 걸리는 작업의 상태에 씁니다.", en: "Use it for uploads, processing, or synchronization that takes time." },
    whenNotToUse: { ko: "즉시 끝나는 동작이나 최종 성공 상태를 표시하는 데 쓰지 않습니다.", en: "Do not use it for instant actions or final success status." },
    accessibility: { ko: "native progress와 보이는 label을 연결하고 알 수 없는 값을 임의로 만들지 않습니다.", en: "Connects native progress with a visible label and never invents a numeric value." },
    sourcePath: "components/ui/progress.tsx",
    demoKey: "progress",
    importExample: 'import { Progress } from "@/components/ui/progress"',
    usageExample: '<Progress label="Upload" value={50} max={200} showValue />',
    relatedComponents: ["spinner", "skeleton", "status-label"],
    dependencies: [],
    states: [
      { id: "determinate", guidance: { ko: "현재 값, 최대값과 표시 백분율이 일치하는지 확인합니다.", en: "Confirm current value, maximum, and displayed percentage agree." } },
      { id: "indeterminate", guidance: { ko: "숫자 없이 진행 중 상태만 전달하는지 확인합니다.", en: "Confirm pending progress is communicated without a false number." } },
      { id: "reduced-motion", guidance: { ko: "움직임 없이도 Primary Blue 구간으로 상태가 보이는지 확인합니다.", en: "Confirm a Primary Blue segment remains visible without motion." } },
    ],
    props: [
      { name: "label", type: "string", required: true, description: { ko: "진행 중인 작업의 보이는 이름입니다.", en: "The visible name of the task in progress." } },
      { name: "value", type: "number", required: false, description: { ko: "현재 진행값이며 생략하면 indeterminate 상태입니다.", en: "The current value; omit it for indeterminate progress." } },
      { name: "max", type: "number", required: false, description: { ko: "완료를 나타내는 최대값입니다.", en: "The maximum value that represents completion." } },
      { name: "showValue", type: "boolean", required: false, description: { ko: "계산된 백분율을 문구로 표시합니다.", en: "Shows the calculated percentage as text." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
