import type { ComponentEntry } from "../schema"

export const coreExpansionComponents = [
  {
    id: "alert-dialog",
    name: "Alert Dialog",
    category: "overlay",
    maturity: "candidate",
    summary: { ko: "되돌리기 어려운 행동 전에 명시적인 결정을 받습니다.", en: "Requests an explicit decision before a consequential action." },
    whenToUse: { ko: "삭제나 권한 변경처럼 결과가 크고 즉시 실행되는 행동에 씁니다.", en: "Use it for immediate, consequential actions such as deletion or permission changes." },
    whenNotToUse: { ko: "일반 안내나 쉽게 되돌릴 수 있는 행동에는 Dialog나 Alert를 씁니다.", en: "Use Dialog or Alert for general information or easily reversible actions." },
    accessibility: { ko: "alertdialog 의미, 제목, 설명, 확인과 취소 동작을 제공하고 초점을 복귀합니다.", en: "Provides alertdialog semantics, title, description, explicit actions, and focus restoration." },
    sourcePath: "components/ui/alert-dialog.tsx",
    demoKey: "alert-dialog",
    importExample: 'import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog"',
    usageExample: '<AlertDialog><AlertDialogTrigger>Delete</AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>Delete?</AlertDialogTitle><AlertDialogDescription>This cannot be undone.</AlertDialogDescription><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive">Delete</AlertDialogAction></AlertDialogContent></AlertDialog>',
    relatedComponents: ["dialog", "alert", "button"],
    dependencies: ["radix-ui"],
    states: [
      { id: "closed", guidance: { ko: "트리거가 결과를 구체적으로 설명하는지 확인합니다.", en: "Confirm the trigger names the consequence clearly." } },
      { id: "open", guidance: { ko: "취소와 실행의 차이, 초기 초점과 초점 복귀를 확인합니다.", en: "Inspect action hierarchy, initial focus, and focus restoration." } },
      { id: "destructive", guidance: { ko: "위험 색상만이 아니라 문구로 결과를 설명합니다.", en: "Explain the consequence in text instead of relying on danger color." } },
    ],
    props: [
      { name: "open", type: "boolean", required: false, description: { ko: "제어되는 열림 상태입니다.", en: "The controlled open state." } },
      { name: "onOpenChange", type: "(open: boolean) => void", required: false, description: { ko: "열림 상태가 바뀔 때 호출됩니다.", en: "Called when open state changes." } },
      { name: "variant", type: '"primary" | "destructive"', required: false, description: { ko: "확인 동작의 의미 색상입니다.", en: "The semantic treatment of the confirmation action." } },
    ],
  },
  {
    id: "popover",
    name: "Popover",
    category: "overlay",
    maturity: "candidate",
    summary: { ko: "현재 맥락 옆에 짧은 정보나 조작을 펼칩니다.", en: "Opens compact information or controls beside the current context." },
    whenToUse: { ko: "필터나 짧은 설정처럼 페이지 이동이 필요 없는 보조 작업에 씁니다.", en: "Use it for supporting tasks such as filters or compact settings." },
    whenNotToUse: { ko: "긴 폼, 중요한 확인, 단순 명령 목록에는 각각 Dialog, Alert Dialog, Dropdown Menu를 씁니다.", en: "Use Dialog, Alert Dialog, or Dropdown Menu for long forms, confirmations, or command lists." },
    accessibility: { ko: "제목과 설명으로 보조 화면의 목적을 알리고 Escape와 초점 복귀를 유지합니다.", en: "Names the supporting surface and preserves Escape dismissal and focus restoration." },
    sourcePath: "components/ui/popover.tsx",
    demoKey: "popover",
    importExample: 'import { Popover, PopoverTrigger, PopoverContent, PopoverTitle, PopoverDescription } from "@/components/ui/popover"',
    usageExample: '<Popover><PopoverTrigger>Filters</PopoverTrigger><PopoverContent><PopoverTitle>Filters</PopoverTitle><PopoverDescription>Narrow results.</PopoverDescription></PopoverContent></Popover>',
    relatedComponents: ["dropdown-menu", "dialog", "tooltip"],
    dependencies: ["radix-ui"],
    states: [
      { id: "closed", guidance: { ko: "트리거 이름만으로 펼쳐질 내용을 예상할 수 있는지 확인합니다.", en: "Confirm the trigger name predicts the content it opens." } },
      { id: "open", guidance: { ko: "화면 가장자리 충돌과 키보드 이동을 확인합니다.", en: "Inspect viewport collision and keyboard movement." } },
    ],
    props: [
      { name: "open", type: "boolean", required: false, description: { ko: "제어되는 열림 상태입니다.", en: "The controlled open state." } },
      { name: "sideOffset", type: "number", required: false, description: { ko: "트리거와 표면 사이 간격입니다.", en: "The distance between trigger and surface." } },
      { name: "align", type: '"start" | "center" | "end"', required: false, description: { ko: "트리거 기준 정렬입니다.", en: "Alignment relative to the trigger." } },
    ],
  },
  {
    id: "side-panel",
    name: "Side Panel",
    category: "overlay",
    maturity: "candidate",
    summary: { ko: "페이지 맥락을 유지한 채 가장자리에서 넓은 작업 공간을 엽니다.", en: "Opens a larger workspace from a viewport edge without leaving the page." },
    whenToUse: { ko: "설정, 상세 정보, 편집처럼 Popover보다 넓은 보조 작업에 씁니다.", en: "Use it for settings, details, or editing that need more room than a Popover." },
    whenNotToUse: { ko: "핵심 페이지 흐름이나 여러 단계 작업을 패널에 가두지 않습니다.", en: "Do not confine a primary page flow or complex multi-step task to a panel." },
    accessibility: { ko: "Dialog의 제목, 설명, 초점 가두기, Escape 닫기와 초점 복귀를 유지합니다.", en: "Preserves Dialog title, description, focus trap, Escape dismissal, and focus restoration." },
    sourcePath: "components/ui/side-panel.tsx",
    demoKey: "side-panel",
    importExample: 'import { SidePanel, SidePanelTrigger, SidePanelContent, SidePanelTitle, SidePanelDescription } from "@/components/ui/side-panel"',
    usageExample: '<SidePanel><SidePanelTrigger>Settings</SidePanelTrigger><SidePanelContent closeLabel="Close"><SidePanelTitle>Settings</SidePanelTitle><SidePanelDescription>Manage the workspace.</SidePanelDescription></SidePanelContent></SidePanel>',
    relatedComponents: ["dialog", "popover", "panel"],
    dependencies: ["@phosphor-icons/react", "radix-ui"],
    states: [
      { id: "closed", guidance: { ko: "트리거가 보조 작업임을 분명히 하는지 확인합니다.", en: "Confirm the trigger clearly names the supporting task." } },
      { id: "open", guidance: { ko: "본문과 패널의 경계, 내부 스크롤과 닫기 동작을 확인합니다.", en: "Inspect the page boundary, internal scroll, and close action." } },
    ],
    props: [
      { name: "side", type: '"top" | "right" | "bottom" | "left"', required: false, description: { ko: "패널이 들어오는 화면 가장자리입니다.", en: "The viewport edge the panel enters from." } },
      { name: "closeLabel", type: "string", required: true, description: { ko: "닫기 아이콘의 접근 가능한 이름입니다.", en: "The accessible name for the close icon." } },
      { name: "open", type: "boolean", required: false, description: { ko: "제어되는 열림 상태입니다.", en: "The controlled open state." } },
    ],
  },
  {
    id: "combobox",
    name: "Combobox",
    category: "form",
    maturity: "candidate",
    summary: { ko: "검색 가능한 긴 목록에서 하나의 값을 고릅니다.", en: "Selects one value from a searchable list." },
    whenToUse: { ko: "선택지가 많거나 사용자가 정확한 이름을 모를 수 있을 때 씁니다.", en: "Use it when the option list is long or labels may be unfamiliar." },
    whenNotToUse: { ko: "짧고 고정된 목록에는 Native Select나 Select를 씁니다.", en: "Use Native Select or Select for short, fixed option lists." },
    accessibility: { ko: "combobox와 listbox 관계, 활성 항목, 선택 상태와 방향키 조작을 제공합니다.", en: "Exposes combobox/listbox relationships, active option, selection, and arrow-key operation." },
    sourcePath: "components/ui/combobox.tsx",
    demoKey: "combobox",
    importExample: 'import { Combobox, type ComboboxOption } from "@/components/ui/combobox"',
    usageExample: '<Combobox aria-label="Framework" options={options} value={value} onValueChange={setValue} emptyText="No results" />',
    relatedComponents: ["field", "select", "input"],
    dependencies: ["@phosphor-icons/react", "radix-ui"],
    states: [
      { id: "closed", guidance: { ko: "선택값과 입력 목적이 함께 읽히는지 확인합니다.", en: "Confirm the selected value and input purpose are both readable." } },
      { id: "open", guidance: { ko: "활성 항목, 선택 항목, 비활성 항목을 구분합니다.", en: "Distinguish active, selected, and disabled options." } },
      { id: "empty", guidance: { ko: "검색 결과가 없음을 짧은 문장으로 알립니다.", en: "State an empty search result in concise text." } },
    ],
    props: [
      { name: "options", type: "readonly ComboboxOption[]", required: true, description: { ko: "검색하고 선택할 항목입니다.", en: "The options available for search and selection." } },
      { name: "value", type: "string", required: false, description: { ko: "제어되는 선택값입니다.", en: "The controlled selected value." } },
      { name: "onValueChange", type: "(value: string) => void", required: false, description: { ko: "선택값이 바뀔 때 호출됩니다.", en: "Called when the selected value changes." } },
      { name: "emptyText", type: "string", required: true, description: { ko: "검색 결과가 없을 때 표시할 문구입니다.", en: "Copy shown when no option matches." } },
    ],
  },
  {
    id: "input-group",
    name: "Input Group",
    category: "form",
    maturity: "candidate",
    summary: { ko: "입력과 단위, 접두어, 짧은 동작을 하나의 컨트롤로 묶습니다.", en: "Groups an input with a unit, prefix, or compact action." },
    whenToUse: { ko: "URL 접두어, 단위, 검증 버튼처럼 입력과 직접 연결된 요소에 씁니다.", en: "Use it for prefixes, units, or actions directly tied to an input." },
    whenNotToUse: { ko: "서로 독립적인 입력이나 여러 주요 행동을 한 경계 안에 넣지 않습니다.", en: "Do not place independent fields or several primary actions inside one boundary." },
    accessibility: { ko: "실제 입력은 하나만 두고 장식 텍스트는 중복 읽히지 않게 처리합니다.", en: "Keeps one native input and prevents decorative text from being announced twice." },
    sourcePath: "components/ui/input-group.tsx",
    demoKey: "input-group",
    importExample: 'import { InputGroup, InputGroupAddon, InputGroupInput, InputGroupButton, InputGroupText } from "@/components/ui/input-group"',
    usageExample: '<InputGroup><InputGroupAddon><InputGroupText>https://</InputGroupText></InputGroupAddon><InputGroupInput aria-label="Domain" /><InputGroupAddon placement="end"><InputGroupButton>Verify</InputGroupButton></InputGroupAddon></InputGroup>',
    relatedComponents: ["field", "input", "button"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "접두어와 동작이 입력값과 시각적으로 연결되는지 확인합니다.", en: "Confirm prefixes and actions remain visibly connected to the value." } },
      { id: "focus-visible", guidance: { ko: "그룹 전체 경계가 초점 상태를 보여주는지 확인합니다.", en: "Confirm the shared boundary communicates focus." } },
      { id: "invalid", guidance: { ko: "Field 오류와 그룹 경계가 같은 상태를 전달하는지 확인합니다.", en: "Confirm Field error copy and group border communicate the same state." } },
    ],
    props: [
      { name: "placement", type: '"start" | "end"', required: false, description: { ko: "Addon이 입력 앞이나 뒤에 배치되는지 정합니다.", en: "Places an addon before or after the input." } },
      { name: "children", type: "ReactNode", required: false, description: { ko: "Input, Addon, Text, Button 조합입니다.", en: "A composition of Input, Addon, Text, and Button parts." } },
    ],
  },
  {
    id: "breadcrumb",
    name: "Breadcrumb",
    category: "navigation",
    maturity: "candidate",
    summary: { ko: "현재 페이지가 정보 구조에서 어디에 있는지 보여줍니다.", en: "Shows where the current page sits in the information hierarchy." },
    whenToUse: { ko: "두 단계 이상 깊은 문서나 관리 화면에서 상위 경로를 제공할 때 씁니다.", en: "Use it in documents or admin views more than one level deep." },
    whenNotToUse: { ko: "단일 단계 페이지나 진행 단계를 설명하는 용도로 쓰지 않습니다.", en: "Do not use it on a single-level page or as a progress indicator." },
    accessibility: { ko: "이름 있는 nav, 순서 목록, 현재 페이지와 숨겨진 구분자를 사용합니다.", en: "Uses a named nav, ordered list, current-page state, and hidden separators." },
    sourcePath: "components/ui/breadcrumb.tsx",
    demoKey: "breadcrumb",
    importExample: 'import { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb"',
    usageExample: '<Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href="/">Home</BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbPage>Design</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb>',
    relatedComponents: ["text-link", "dropdown-menu"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "default", guidance: { ko: "현재 페이지와 이동 가능한 상위 경로를 구분합니다.", en: "Distinguish the current page from navigable ancestors." } },
      { id: "collapsed", guidance: { ko: "긴 중간 경로는 이름 있는 Ellipsis로 축약합니다.", en: "Collapse long intermediate paths with a named Ellipsis." } },
    ],
    props: [
      { name: "aria-label", type: "string", required: false, description: { ko: "여러 탐색 영역을 구분하는 이름입니다.", en: "A name that distinguishes this navigation region." } },
      { name: "label", type: "string", required: true, description: { ko: "BreadcrumbEllipsis의 접근 가능한 이름입니다.", en: "The accessible name for BreadcrumbEllipsis." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
