import type { ComponentEntry } from "../schema"

export const coreExpansionC2Components = [
  {
    id: "table",
    name: "Table",
    category: "content",
    maturity: "candidate",
    summary: { ko: "열과 행으로 비교해야 하는 정보를 native table로 보여줍니다.", en: "Presents information that must be compared across native table rows and columns." },
    whenToUse: { ko: "상태, 이름, 날짜처럼 같은 속성을 여러 항목에서 비교할 때 씁니다.", en: "Use it to compare the same attributes, such as status, name, or date, across records." },
    whenNotToUse: { ko: "한 항목의 상세 정보나 작은 화면에서 순서만 중요한 목록에는 Item을 씁니다.", en: "Use Item for one record's details or a list whose sequence matters more than column comparison." },
    accessibility: { ko: "caption, thead, tbody, th scope 등 native 표 구조를 유지합니다.", en: "Preserves native caption, thead, tbody, and scoped header semantics." },
    sourcePath: "components/ui/table.tsx",
    demoKey: "table",
    importExample: 'import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"',
    usageExample: '<Table aria-label="Deployments"><TableHeader><TableRow><TableHead>Service</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Laf ID</TableCell></TableRow></TableBody></Table>',
    relatedComponents: ["data-table", "item", "separator"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "열 제목과 행의 대응 관계가 빠르게 읽히는지 확인합니다.", en: "Confirm column headers and row values scan as one relationship." } },
      { id: "overflow", guidance: { ko: "작은 화면에서 표 의미를 유지한 채 가로 스크롤되는지 확인합니다.", en: "Confirm small screens scroll horizontally without breaking table semantics." } },
    ],
    props: [
      { name: "aria-label", type: "string", required: false, description: { ko: "보이는 caption이 없을 때 표의 이름을 제공합니다.", en: "Names the table when no visible caption is present." } },
      { name: "align", type: '"start" | "center" | "end"', required: false, description: { ko: "열 제목과 셀 내용의 정렬입니다.", en: "Aligns header and cell content." } },
      { name: "scope", type: "string", required: false, description: { ko: "TableHead가 설명하는 행이나 열 범위입니다.", en: "The row or column scope described by TableHead." } },
    ],
  },
  {
    id: "data-table",
    name: "Data Table",
    category: "content",
    maturity: "candidate",
    summary: { ko: "정렬과 빈 상태가 필요한 구조화 데이터를 보여줍니다.", en: "Displays structured data with sorting and an explicit empty state." },
    whenToUse: { ko: "관리 목록처럼 사용자가 열 기준으로 데이터를 다시 정렬해야 할 때 씁니다.", en: "Use it for operational lists that people need to reorder by column." },
    whenNotToUse: { ko: "정적 비교에는 Table을, 카드형 탐색에는 Item을 씁니다.", en: "Use Table for static comparison and Item for editorial browsing." },
    accessibility: { ko: "정렬 버튼과 aria-sort를 연결하고 실제 Table 구조를 유지합니다.", en: "Connects sort buttons with aria-sort while preserving real Table semantics." },
    sourcePath: "components/ui/data-table.tsx",
    demoKey: "data-table",
    importExample: 'import { DataTable, type DataTableColumn } from "@/components/ui/data-table"',
    usageExample: '<DataTable aria-label="Services" columns={columns} rows={rows} getRowKey={(row) => row.id} emptyText="No services" />',
    relatedComponents: ["table", "pagination", "empty-state"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "default", guidance: { ko: "정렬 가능한 열과 정적 열을 구분합니다.", en: "Distinguish sortable columns from static columns." } },
      { id: "sorted", guidance: { ko: "현재 정렬 열과 방향이 아이콘과 접근성 트리에 함께 나타나는지 확인합니다.", en: "Confirm the active column and direction appear visually and in the accessibility tree." } },
      { id: "empty", guidance: { ko: "빈 상태가 모든 열을 가로질러 짧게 설명되는지 확인합니다.", en: "Confirm the empty state spans the table with concise copy." } },
    ],
    props: [
      { name: "columns", type: "readonly DataTableColumn<Row>[]", required: true, description: { ko: "셀 렌더링과 선택적 정렬값을 정의합니다.", en: "Defines cell rendering and optional sort values." } },
      { name: "rows", type: "readonly Row[]", required: true, description: { ko: "표에 표시할 실제 데이터입니다.", en: "The real records displayed by the table." } },
      { name: "getRowKey", type: "(row: Row) => string", required: true, description: { ko: "각 행의 안정적인 식별자를 반환합니다.", en: "Returns a stable identifier for each row." } },
      { name: "emptyText", type: "string", required: true, description: { ko: "표시할 행이 없을 때의 안내입니다.", en: "Copy shown when there are no rows." } },
    ],
  },
  {
    id: "pagination",
    name: "Pagination",
    category: "navigation",
    maturity: "candidate",
    summary: { ko: "큰 컬렉션의 이전, 다음, 특정 페이지로 이동합니다.", en: "Navigates to previous, next, or specific pages in a large collection." },
    whenToUse: { ko: "목록을 여러 URL 페이지로 나누고 위치를 직접 이동해야 할 때 씁니다.", en: "Use it when a collection is split across URL-addressable pages." },
    whenNotToUse: { ko: "슬라이드 전환이나 현재 화면 안의 탭에는 쓰지 않습니다.", en: "Do not use it for slides or in-page tab switching." },
    accessibility: { ko: "이름 있는 nav, 실제 링크, aria-current와 이름 있는 축약 표시를 사용합니다.", en: "Uses a named nav, real links, aria-current, and a named ellipsis." },
    sourcePath: "components/ui/pagination.tsx",
    demoKey: "pagination",
    importExample: 'import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationPrevious, PaginationNext } from "@/components/ui/pagination"',
    usageExample: '<Pagination aria-label="Pages"><PaginationContent><PaginationItem><PaginationLink href="?page=2" isCurrent>2</PaginationLink></PaginationItem></PaginationContent></Pagination>',
    relatedComponents: ["data-table", "breadcrumb", "text-link"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "default", guidance: { ko: "이전과 다음 목적지가 링크로 동작하는지 확인합니다.", en: "Confirm previous and next destinations remain real links." } },
      { id: "current", guidance: { ko: "현재 페이지가 너비와 색뿐 아니라 aria-current로 전달되는지 확인합니다.", en: "Confirm the current page is exposed through aria-current, not only shape and color." } },
      { id: "collapsed", guidance: { ko: "긴 범위를 Ellipsis로 축약하되 현재 위치는 유지합니다.", en: "Collapse long ranges with Ellipsis while preserving the current position." } },
    ],
    props: [
      { name: "isCurrent", type: "boolean", required: false, description: { ko: "현재 페이지 링크를 표시합니다.", en: "Marks the current page link." } },
      { name: "label", type: "string", required: true, description: { ko: "방향 링크나 축약 표시의 접근 가능한 이름입니다.", en: "The accessible name for direction links or ellipsis." } },
    ],
  },
  {
    id: "item",
    name: "Item",
    category: "structure",
    maturity: "candidate",
    summary: { ko: "미디어, 본문, 메타데이터와 동작을 하나의 행으로 구성합니다.", en: "Composes media, copy, metadata, and actions into one row." },
    whenToUse: { ko: "저장소, 문서, 사람처럼 반복되는 개체를 카드 없이 나열할 때 씁니다.", en: "Use it for repeated entities such as repositories, documents, or people without card grids." },
    whenNotToUse: { ko: "열 비교가 핵심이면 Table을, 독립된 영역이면 Panel을 씁니다.", en: "Use Table for column comparison and Panel for a standalone region." },
    accessibility: { ko: "주변 목록에 맞는 article, div, li 요소를 선택하고 제목으로 이름을 연결합니다.", en: "Chooses article, div, or li for the surrounding structure and labels the item from its title." },
    sourcePath: "components/ui/item.tsx",
    demoKey: "item",
    importExample: 'import { Item, ItemMedia, ItemContent, ItemTitle, ItemDescription, ItemActions } from "@/components/ui/item"',
    usageExample: '<Item as="li"><ItemMedia>LF</ItemMedia><ItemContent><ItemTitle>lafetch</ItemTitle><ItemDescription>Typed fetch utilities.</ItemDescription></ItemContent><ItemActions>Open</ItemActions></Item>',
    relatedComponents: ["panel", "table", "status-label"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "제목, 설명, 메타데이터와 동작의 읽기 순서를 확인합니다.", en: "Inspect the reading order of title, description, metadata, and actions." } },
      { id: "subtle", guidance: { ko: "조용한 면이 인접 행 경계보다 강해지지 않는지 확인합니다.", en: "Confirm the quiet surface does not overpower adjacent row structure." } },
      { id: "inverse", guidance: { ko: "Ink 면에서 본문과 보조 문구 대비를 확인합니다.", en: "Verify primary and supporting copy contrast on the Ink surface." } },
    ],
    props: [
      { name: "as", type: '"article" | "div" | "li"', required: false, description: { ko: "주변 문서 구조에 맞는 HTML 요소입니다.", en: "The HTML element that fits the surrounding document structure." } },
      { name: "tone", type: '"default" | "subtle" | "inverse"', required: false, description: { ko: "행의 표면 대비입니다.", en: "The surface contrast of the row." } },
    ],
  },
  {
    id: "spinner",
    name: "Spinner",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "작은 영역에서 완료 시점을 알 수 없는 진행 중 상태를 알립니다.", en: "Signals indeterminate progress in a compact area." },
    whenToUse: { ko: "버튼이나 짧은 인라인 작업처럼 Skeleton을 쓰기 어려운 곳에 씁니다.", en: "Use it inside a button or compact inline task where Skeleton is unsuitable." },
    whenNotToUse: { ko: "페이지 전체 로딩이나 진행률을 아는 작업에는 Skeleton이나 Progress를 씁니다.", en: "Use Skeleton for page loading and Progress when completion can be measured." },
    accessibility: { ko: "status 역할과 구체적인 label을 제공하고 회전 아이콘은 숨깁니다.", en: "Provides a named status and hides the rotating icon from assistive technology." },
    sourcePath: "components/ui/spinner.tsx",
    demoKey: "spinner",
    importExample: 'import { Spinner } from "@/components/ui/spinner"',
    usageExample: '<Spinner label="Saving document" size="compact" />',
    relatedComponents: ["progress", "skeleton", "button"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "compact", guidance: { ko: "버튼 안에서도 label이 구체적인지 확인합니다.", en: "Confirm the label remains specific when used inside a button." } },
      { id: "default", guidance: { ko: "주변 문구보다 로딩 표시가 과도하게 커지지 않는지 확인합니다.", en: "Confirm the indicator does not overpower surrounding copy." } },
      { id: "reduced-motion", guidance: { ko: "회전을 멈춰도 이름 있는 status로 진행 중 의미가 유지되는지 확인합니다.", en: "Confirm the named status preserves the pending meaning when rotation stops." } },
    ],
    props: [
      { name: "label", type: "string", required: true, description: { ko: "진행 중인 작업의 접근 가능한 이름입니다.", en: "The accessible name of the pending task." } },
      { name: "size", type: '"compact" | "default" | "large"', required: false, description: { ko: "표시 크기입니다.", en: "The indicator size." } },
    ],
  },
  {
    id: "progress",
    name: "Progress",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "측정 가능한 작업의 진행률이나 연결 중 상태를 보여줍니다.", en: "Shows measurable completion or an indeterminate connection state." },
    whenToUse: { ko: "업로드, 처리, 동기화처럼 시간이 걸리는 작업의 상태에 씁니다.", en: "Use it for uploads, processing, or synchronization that takes time." },
    whenNotToUse: { ko: "즉시 끝나는 동작이나 최종 성공 상태를 표시하는 데 쓰지 않습니다.", en: "Do not use it for instant actions or final success status." },
    accessibility: { ko: "native progress와 보이는 label을 연결하고 알 수 없는 값을 임의로 만들지 않습니다.", en: "Connects native progress with a visible label and never invents a numeric value." },
    sourcePath: "components/ui/progress.tsx",
    demoKey: "progress",
    importExample: 'import { Progress } from "@/components/ui/progress"',
    usageExample: '<Progress label="Upload" value={50} max={200} showValue />',
    relatedComponents: ["spinner", "skeleton", "status-label"],
    dependencies: [],
    states: [
      { id: "determinate", guidance: { ko: "현재 값, 최대값과 표시 백분율이 일치하는지 확인합니다.", en: "Confirm current value, maximum, and displayed percentage agree." } },
      { id: "indeterminate", guidance: { ko: "숫자 없이 진행 중 상태만 전달하는지 확인합니다.", en: "Confirm pending progress is communicated without a false number." } },
      { id: "reduced-motion", guidance: { ko: "움직임 없이도 Primary Blue 구간으로 상태가 보이는지 확인합니다.", en: "Confirm a Primary Blue segment remains visible without motion." } },
    ],
    props: [
      { name: "label", type: "string", required: true, description: { ko: "진행 중인 작업의 보이는 이름입니다.", en: "The visible name of the task in progress." } },
      { name: "value", type: "number", required: false, description: { ko: "현재 진행값이며 생략하면 indeterminate 상태입니다.", en: "The current value; omit it for indeterminate progress." } },
      { name: "max", type: "number", required: false, description: { ko: "완료를 나타내는 최대값입니다.", en: "The maximum value that represents completion." } },
      { name: "showValue", type: "boolean", required: false, description: { ko: "계산된 백분율을 문구로 표시합니다.", en: "Shows the calculated percentage as text." } },
    ],
  },
  {
    id: "notice-toast",
    name: "Notice Toast",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "현재 작업을 막지 않고 짧은 결과를 알립니다.", en: "Announces a brief result without blocking the current task." },
    whenToUse: { ko: "저장, 발행, 복사처럼 이미 끝난 동작의 짧은 결과에 씁니다.", en: "Use it for brief outcomes of completed actions such as save, publish, or copy." },
    whenNotToUse: { ko: "폼 오류, 복구가 필요한 실패, 반드시 읽어야 하는 안내에는 Alert를 씁니다.", en: "Use Alert for form errors, recoverable failures, or information that must remain visible." },
    accessibility: { ko: "일반 알림은 status, 오류는 alert로 알리고 항상 닫기 동작을 제공합니다.", en: "Uses status for routine notices, alert for errors, and always provides dismissal." },
    sourcePath: "components/ui/notice-toast.tsx",
    demoKey: "notice-toast",
    importExample: 'import { NoticeToastProvider, useNoticeToast } from "@/components/ui/notice-toast"',
    usageExample: 'const { notify } = useNoticeToast(); notify({ title: "Published", variant: "success" })',
    relatedComponents: ["alert", "status-label", "spinner"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "info", guidance: { ko: "보조 정보가 현재 작업을 가리지 않는지 확인합니다.", en: "Confirm supporting information does not obstruct the current task." } },
      { id: "success", guidance: { ko: "완료 결과를 한 문장으로 설명합니다.", en: "Describe the completed outcome in one sentence." } },
      { id: "warning", guidance: { ko: "필요한 후속 행동이 있다면 설명에 명시합니다.", en: "State any required follow-up action in the description." } },
      { id: "error", guidance: { ko: "긴 복구 절차는 Toast에 넣지 않고 지속되는 Alert로 연결합니다.", en: "Move long recovery instructions to a persistent Alert." } },
    ],
    props: [
      { name: "notify", type: "(notice: NoticeToastInput) => string", required: true, description: { ko: "알림을 큐에 추가하고 ID를 반환합니다.", en: "Adds a notice to the queue and returns its ID." } },
      { name: "duration", type: "number", required: false, description: { ko: "자동 해제 시간이며 0이면 직접 닫을 때까지 유지됩니다.", en: "Auto-dismiss duration; zero persists until manually dismissed." } },
      { name: "variant", type: '"info" | "success" | "warning" | "error"', required: false, description: { ko: "알림의 의미 상태입니다.", en: "The semantic notice state." } },
      { name: "closeLabel", type: "string", required: true, description: { ko: "닫기 아이콘의 번역된 이름입니다.", en: "The localized name of the close control." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
