import type { ComponentEntry } from "../schema"

export const feedbackComponents = [
  {
    id: "alert",
    name: "Alert",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "중요한 상태와 다음 행동을 명확하게 알립니다.", en: "Communicates an important state and the next action." },
    whenToUse: { ko: "정보, 성공, 주의, 오류를 본문 흐름 안에서 설명할 때 씁니다.", en: "Use it for inline information, success, warning, or error feedback." },
    whenNotToUse: { ko: "모든 안내를 실시간 경고로 발표하거나 장식 강조에 쓰지 않습니다.", en: "Do not announce every note live or use it as decorative emphasis." },
    accessibility: { ko: "상태는 아이콘과 제목으로 함께 알리고 새 오류만 live alert로 발표합니다.", en: "Pair icon and visible title, and announce only new urgent feedback live." },
    sourcePath: "components/ui/alert.tsx",
    demoKey: "alert",
    importExample: 'import { Alert } from "@/components/ui/alert"',
    usageExample: '<Alert title="Save failed" variant="error" live>Try again.</Alert>',
    relatedComponents: ["button", "empty-state"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "info", guidance: { ko: "정보 상태가 Info 색과 제목으로 구분되는지 확인합니다.", en: "Confirm informational feedback uses its icon, color, and title." } },
      { id: "success", guidance: { ko: "완료 결과를 짧고 구체적으로 설명하는지 확인합니다.", en: "Confirm successful outcomes are concise and concrete." } },
      { id: "warning", guidance: { ko: "주의 상태가 오류로 오인되지 않는지 확인합니다.", en: "Confirm warning feedback is not mistaken for an error." } },
      { id: "error", guidance: { ko: "오류 원인과 가능한 다음 행동을 확인합니다.", en: "Confirm the error and available next action are clear." } },
      { id: "live", guidance: { ko: "새로 발생한 긴급 상태만 alert로 발표되는지 확인합니다.", en: "Confirm only newly triggered urgent feedback uses role alert." } },
    ],
    props: [
      { name: "title", type: "ReactNode", required: true, description: { ko: "상태를 요약하는 보이는 제목입니다.", en: "A visible title that summarizes the state." } },
      { name: "variant", type: '"info" | "success" | "warning" | "error"', required: false, description: { ko: "상태의 의미론적 종류입니다.", en: "The semantic feedback variant." } },
      { name: "live", type: "boolean", required: false, description: { ko: "새 상태를 즉시 발표할지 정합니다.", en: "Whether to announce newly rendered feedback immediately." } },
    ],
  },
  {
    id: "skeleton",
    name: "Skeleton",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "콘텐츠 구조가 불러와지는 동안 자리를 유지합니다.", en: "Reserves content structure while data is loading." },
    whenToUse: { ko: "최종 레이아웃의 크기를 알고 짧게 기다릴 때 씁니다.", en: "Use it for brief loading when the final layout shape is known." },
    whenNotToUse: { ko: "오래 걸리는 작업의 진행률이나 빈 상태를 대신하지 않습니다.", en: "Do not replace progress feedback or an empty state with a skeleton." },
    accessibility: { ko: "보조 기술에서는 항상 숨기고 별도 상태 문구로 로딩을 알립니다.", en: "Always hide it from assistive technology and announce loading separately." },
    sourcePath: "components/ui/skeleton.tsx",
    demoKey: "skeleton",
    importExample: 'import { Skeleton } from "@/components/ui/skeleton"',
    usageExample: '<Skeleton style={{ height: 48 }} />',
    relatedComponents: ["empty-state"],
    dependencies: [],
    states: [
      { id: "loading", guidance: { ko: "최종 콘텐츠와 비슷한 크기로 배치되는지 확인합니다.", en: "Confirm the placeholder matches the final content shape." } },
      { id: "reduced-motion", guidance: { ko: "동작 줄이기에서 정적인 면으로 남는지 확인합니다.", en: "Confirm it remains static when reduced motion is requested." } },
    ],
    props: [
      { name: "className", type: "string", required: false, description: { ko: "구체적인 플레이스홀더 크기와 배치에 씁니다.", en: "Provides layout-specific size and placement." } },
      { name: "style", type: "CSSProperties", required: false, description: { ko: "알려진 최종 크기를 직접 지정할 때 씁니다.", en: "Sets a known final size directly." } },
    ],
  },
  {
    id: "empty-state",
    name: "Empty State",
    category: "feedback",
    maturity: "candidate",
    summary: { ko: "표시할 내용이 없을 때 이유와 다음 행동을 안내합니다.", en: "Explains why no content is present and what can happen next." },
    whenToUse: { ko: "검색 결과, 문서, 목록이 비어 있는 실제 상태에 씁니다.", en: "Use it for a genuinely empty result, document, or collection." },
    whenNotToUse: { ko: "예시 데이터를 꾸며 빈 공간을 채우거나 일반 홍보 영역으로 쓰지 않습니다.", en: "Do not invent example data or use it as a promotional card." },
    accessibility: { ko: "제목과 설명만으로 상태를 이해할 수 있고 가능할 때 복구 동작을 제공합니다.", en: "Make the state understandable from title and description, with recovery when available." },
    sourcePath: "components/ui/empty-state.tsx",
    demoKey: "empty-state",
    importExample: 'import { EmptyState } from "@/components/ui/empty-state"',
    usageExample: '<EmptyState title="No documents" description="Create the first document." action={<Button>Create</Button>} />',
    relatedComponents: ["button", "text-link", "skeleton"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "제목과 설명이 원인을 구체적으로 말하는지 확인합니다.", en: "Confirm title and description state the reason concretely." } },
      { id: "action", guidance: { ko: "가능한 다음 행동이 하나의 명확한 버튼으로 제공되는지 확인합니다.", en: "Confirm one clear next action is provided when recovery is possible." } },
    ],
    props: [
      { name: "title", type: "ReactNode", required: true, description: { ko: "빈 상태를 요약하는 제목입니다.", en: "A title that summarizes the empty state." } },
      { name: "description", type: "ReactNode", required: true, description: { ko: "이유나 다음 단계를 설명합니다.", en: "Explains the reason or next step." } },
      { name: "action", type: "ReactNode", required: false, description: { ko: "복구나 생성으로 이어지는 동작입니다.", en: "An action for recovery or creation." } },
    ],
  },
  {
    id: "separator",
    name: "Separator",
    category: "structure",
    maturity: "candidate",
    summary: { ko: "콘텐츠 사이의 시각적 또는 의미적 경계를 만듭니다.", en: "Creates a visual or semantic boundary between content." },
    whenToUse: { ko: "간격만으로 관계를 구분하기 어려운 행과 구간 사이에 씁니다.", en: "Use it when spacing alone cannot distinguish rows or sections." },
    whenNotToUse: { ko: "모든 요소를 선으로 둘러싸거나 의미 없는 장식으로 반복하지 않습니다.", en: "Do not box every element or repeat rules as decoration." },
    accessibility: { ko: "기본은 장식으로 숨기고 구분 자체가 의미일 때만 separator로 노출합니다.", en: "Hide it by default and expose a separator only when the boundary carries meaning." },
    sourcePath: "components/ui/separator.tsx",
    demoKey: "separator",
    importExample: 'import { Separator } from "@/components/ui/separator"',
    usageExample: '<Separator decorative={false} />',
    relatedComponents: ["empty-state"],
    dependencies: [],
    states: [
      { id: "decorative", guidance: { ko: "보조 기술에서 숨겨진 1px 선인지 확인합니다.", en: "Confirm the one-pixel rule is hidden from assistive technology." } },
      { id: "horizontal", guidance: { ko: "의미 있는 가로 경계가 hr로 노출되는지 확인합니다.", en: "Confirm a meaningful horizontal boundary renders as hr." } },
      { id: "vertical", guidance: { ko: "세로 경계의 orientation이 전달되는지 확인합니다.", en: "Confirm vertical orientation is exposed semantically." } },
    ],
    props: [
      { name: "decorative", type: "boolean", required: false, description: { ko: "기본값 true이며 보조 기술에서 숨깁니다.", en: "Defaults to true and hides the rule from assistive technology." } },
      { name: "orientation", type: '"horizontal" | "vertical"', required: false, description: { ko: "선의 방향입니다.", en: "The separator direction." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
