import type { ComponentEntry } from "../schema"

export const formComponents = [
  {
    id: "field",
    name: "Field",
    category: "form",
    maturity: "candidate",
    summary: { ko: "레이블, 입력, 설명, 오류를 한 관계로 묶습니다.", en: "Connects a label, control, description, and error as one field." },
    whenToUse: { ko: "사용자가 값을 입력하거나 선택해야 하는 폼 항목에 씁니다.", en: "Use it for a form item where a person enters or selects a value." },
    whenNotToUse: { ko: "읽기 전용 정보나 여러 입력을 하나의 레이블로 뭉칠 때는 쓰지 않습니다.", en: "Do not use it for read-only content or unrelated controls under one label." },
    accessibility: { ko: "직접 자식인 설명과 오류의 ID를 입력 요소에 연결합니다.", en: "Links direct description and error children to the nested control." },
    sourcePath: "components/ui/field.tsx",
    demoKey: "field",
    importExample: 'import { Field, FieldLabel, FieldDescription, FieldError } from "@/components/ui/field"',
    usageExample: '<Field required><FieldLabel>Email</FieldLabel><Input /><FieldDescription>Work email</FieldDescription></Field>',
    relatedComponents: ["label", "input", "textarea", "native-select"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "레이블과 입력이 하나의 항목으로 읽히는지 확인합니다.", en: "Confirm label and control are exposed as one field." } },
      { id: "required", guidance: { ko: "필수 표시와 native required 상태를 함께 확인합니다.", en: "Check the visible marker and native required state together." } },
      { id: "invalid", guidance: { ko: "오류 문구와 aria-invalid 연결을 확인합니다.", en: "Check error copy and aria-invalid linkage." } },
    ],
    props: [
      { name: "required", type: "boolean", required: false, description: { ko: "중첩 컨트롤의 필수 상태입니다.", en: "Sets the required state for the nested control." } },
      { name: "invalid", type: "boolean", required: false, description: { ko: "오류 상태와 오류 설명 연결을 활성화합니다.", en: "Enables invalid state and error relationships." } },
      { name: "children", type: "ReactNode", required: false, description: { ko: "직접 배치한 Field 복합 요소입니다.", en: "Direct Field compound parts and a control." } },
    ],
  },
  {
    id: "label",
    name: "Label",
    category: "form",
    maturity: "candidate",
    summary: { ko: "입력 요소의 목적을 짧게 설명합니다.", en: "Provides a concise name for a form control." },
    whenToUse: { ko: "Field 밖에서 native 입력과 명시적으로 연결할 때 씁니다.", en: "Use it to explicitly name a native control outside Field." },
    whenNotToUse: { ko: "설명 문구나 시각 장식만을 위해 label 요소를 쓰지 않습니다.", en: "Do not use a label element for help text or decoration." },
    accessibility: { ko: "htmlFor와 입력 id를 같은 값으로 유지합니다.", en: "Keep htmlFor equal to the target control ID." },
    sourcePath: "components/ui/field.tsx",
    demoKey: "label",
    importExample: 'import { Label } from "@/components/ui/field"',
    usageExample: '<><Label htmlFor="query">Search</Label><Input id="query" /></>',
    relatedComponents: ["field", "input", "textarea", "native-select"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "레이블 선택 시 연결된 입력으로 초점이 이동하는지 확인합니다.", en: "Confirm activating the label focuses its control." } },
      { id: "required", guidance: { ko: "FieldLabel의 필수 표시가 텍스트 의미를 방해하지 않는지 확인합니다.", en: "Confirm FieldLabel's required marker does not obscure its name." } },
    ],
    props: [
      { name: "htmlFor", type: "string", required: false, description: { ko: "연결할 컨트롤의 id입니다.", en: "The ID of the associated control." } },
      { name: "children", type: "ReactNode", required: false, description: { ko: "컨트롤을 설명하는 짧은 이름입니다.", en: "A concise name for the control." } },
    ],
  },
  {
    id: "input",
    name: "Input",
    category: "form",
    maturity: "candidate",
    summary: { ko: "한 줄 값을 입력받는 native input입니다.", en: "A native input for single-line values." },
    whenToUse: { ko: "이메일, 제목, 검색어처럼 한 줄로 끝나는 값에 씁니다.", en: "Use it for single-line values such as email, title, or search." },
    whenNotToUse: { ko: "여러 줄 문장에는 Textarea를, 정해진 선택에는 Native Select를 씁니다.", en: "Use Textarea for multiline copy and Native Select for fixed choices." },
    accessibility: { ko: "Field나 Label로 이름을 제공하고 입력 목적에 맞는 type을 지정합니다.", en: "Provide a name through Field or Label and choose the correct native type." },
    sourcePath: "components/ui/input.tsx",
    demoKey: "input",
    importExample: 'import { Input } from "@/components/ui/input"',
    usageExample: '<Input name="email" type="email" autoComplete="email" />',
    relatedComponents: ["field", "label", "textarea", "native-select"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "Paper 바탕, Ink 텍스트, Line 경계를 확인합니다.", en: "Inspect Paper surface, Ink text, and Line border." } },
      { id: "focus-visible", guidance: { ko: "2px Primary 초점선을 확인합니다.", en: "Inspect the two-pixel Primary focus outline." } },
      { id: "invalid", guidance: { ko: "Error 경계와 연결된 오류 문구를 확인합니다.", en: "Inspect the Error border and associated error copy." } },
      { id: "disabled", guidance: { ko: "입력이 막히고 커서와 불투명도가 바뀌는지 확인합니다.", en: "Confirm input is blocked with disabled cursor and opacity." } },
    ],
    props: [
      { name: "type", type: "HTMLInputTypeAttribute", required: false, description: { ko: "값의 native 입력 형식입니다.", en: "The native input type for the value." } },
      { name: "name", type: "string", required: false, description: { ko: "폼 제출에 쓰는 이름입니다.", en: "The name used for form submission." } },
      { name: "placeholder", type: "string", required: false, description: { ko: "레이블을 대신하지 않는 짧은 예시입니다.", en: "A short example that never replaces the label." } },
    ],
  },
  {
    id: "textarea",
    name: "Textarea",
    category: "form",
    maturity: "candidate",
    summary: { ko: "여러 줄의 긴 텍스트를 입력받습니다.", en: "Accepts longer multiline text." },
    whenToUse: { ko: "문의 내용이나 문서 요약처럼 줄바꿈이 필요한 값에 씁니다.", en: "Use it for values that need line breaks, such as inquiries or summaries." },
    whenNotToUse: { ko: "코드 편집기나 한 줄 값에는 쓰지 않습니다.", en: "Do not use it as a code editor or for single-line values." },
    accessibility: { ko: "보이는 레이블을 연결하고 필요하면 글자 수 안내를 설명으로 제공합니다.", en: "Associate a visible label and expose length guidance as a description when needed." },
    sourcePath: "components/ui/textarea.tsx",
    demoKey: "textarea",
    importExample: 'import { Textarea } from "@/components/ui/textarea"',
    usageExample: '<Textarea name="message" rows={6} />',
    relatedComponents: ["field", "label", "input"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "132px 최소 높이와 세로 크기 조절을 확인합니다.", en: "Inspect the 132px minimum height and vertical resize." } },
      { id: "focus-visible", guidance: { ko: "긴 글을 입력해도 초점선과 너비가 유지되는지 확인합니다.", en: "Confirm focus and width remain stable with long content." } },
      { id: "invalid", guidance: { ko: "오류 문구가 입력 내용과 함께 읽히는지 확인합니다.", en: "Confirm error copy is associated with the entered content." } },
    ],
    props: [
      { name: "rows", type: "number", required: false, description: { ko: "초기 표시 줄 수입니다.", en: "The initial visible row count." } },
      { name: "name", type: "string", required: false, description: { ko: "폼 제출에 쓰는 이름입니다.", en: "The name used for form submission." } },
    ],
  },
  {
    id: "native-select",
    name: "Native Select",
    category: "form",
    maturity: "candidate",
    summary: { ko: "브라우저 기본 선택 동작을 유지하는 select입니다.", en: "A select that preserves native browser selection behavior." },
    whenToUse: { ko: "짧고 고정된 선택지를 하나 고를 때 씁니다.", en: "Use it to choose one value from a short, fixed list." },
    whenNotToUse: { ko: "검색이 필요한 긴 목록이나 여러 값을 고르는 UI에는 쓰지 않습니다.", en: "Do not use it for long searchable lists or multi-selection." },
    accessibility: { ko: "native select만 상호작용 요소로 두고 장식 화살표는 숨깁니다.", en: "Keep the native select as the only interactive element and hide its decorative icon." },
    sourcePath: "components/ui/native-select.tsx",
    demoKey: "native-select",
    importExample: 'import { NativeSelect } from "@/components/ui/native-select"',
    usageExample: '<NativeSelect name="category"><option value="general">General</option></NativeSelect>',
    relatedComponents: ["field", "label", "input"],
    dependencies: ["@phosphor-icons/react"],
    states: [
      { id: "default", guidance: { ko: "현재 선택값과 장식 화살표를 확인합니다.", en: "Inspect the current value and decorative caret." } },
      { id: "focus-visible", guidance: { ko: "키보드로 선택 목록을 열고 초점선을 확인합니다.", en: "Open the native list by keyboard and inspect focus." } },
      { id: "disabled", guidance: { ko: "선택이 막히고 값은 읽을 수 있는지 확인합니다.", en: "Confirm selection is blocked while the value remains readable." } },
    ],
    props: [
      { name: "name", type: "string", required: false, description: { ko: "폼 제출에 쓰는 이름입니다.", en: "The name used for form submission." } },
      { name: "children", type: "ReactNode", required: false, description: { ko: "native option과 optgroup입니다.", en: "Native option and optgroup elements." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
