import type { ComponentEntry } from "../schema"

export const selectionComponents = [
  {
    id: "checkbox",
    name: "Checkbox",
    category: "selection",
    maturity: "candidate",
    summary: { ko: "서로 독립적인 선택을 켜고 끕니다.", en: "Turns an independent selection on or off." },
    whenToUse: { ko: "복수 선택, 동의, 목록 선택처럼 각 값이 독립적일 때 씁니다.", en: "Use it for independent consent, list, or multi-select values." },
    whenNotToUse: { ko: "즉시 설정을 바꾸는 단일 동작에는 Switch를 씁니다.", en: "Use Switch for a single setting that changes immediately." },
    accessibility: { ko: "native checkbox를 유지하고 mixed 상태는 aria-checked로 함께 알립니다.", en: "Preserve the native checkbox and expose mixed state through aria-checked." },
    sourcePath: "components/ui/checkbox.tsx",
    demoKey: "checkbox",
    importExample: 'import { Checkbox } from "@/components/ui/checkbox"',
    usageExample: '<Checkbox label="Select all" indeterminate />',
    relatedComponents: ["radio-group", "switch"],
    dependencies: [],
    states: [
      { id: "unchecked", guidance: { ko: "이름과 선택되지 않은 사각 컨트롤을 확인합니다.", en: "Inspect the label and unchecked square control." } },
      { id: "checked", guidance: { ko: "선택 상태가 색에만 의존하지 않는지 확인합니다.", en: "Confirm selected state is not communicated by color alone." } },
      { id: "indeterminate", guidance: { ko: "부분 선택이 mixed 상태로 전달되는지 확인합니다.", en: "Confirm partial selection is exposed as mixed." } },
      { id: "disabled", guidance: { ko: "비활성 컨트롤이 실행되지 않는지 확인합니다.", en: "Confirm the disabled control cannot change." } },
    ],
    props: [
      { name: "label", type: "ReactNode", required: true, description: { ko: "선택값을 설명하는 보이는 이름입니다.", en: "The visible name of the selection." } },
      { name: "description", type: "ReactNode", required: false, description: { ko: "선택 결과를 설명하는 보조 문구입니다.", en: "Supporting copy that explains the consequence." } },
      { name: "indeterminate", type: "boolean", required: false, description: { ko: "일부만 선택된 mixed 상태입니다.", en: "The mixed state for a partial selection." } },
    ],
  },
  {
    id: "radio-group",
    name: "Radio Group",
    category: "selection",
    maturity: "candidate",
    summary: { ko: "한 그룹에서 하나의 값만 고릅니다.", en: "Selects exactly one value from a named group." },
    whenToUse: { ko: "선택지가 적고 모두 한눈에 비교되어야 할 때 씁니다.", en: "Use it when a short list of options should stay visible for comparison." },
    whenNotToUse: { ko: "공간이 좁거나 선택지가 많으면 Native Select를 씁니다.", en: "Use Native Select when space is tight or the list is long." },
    accessibility: { ko: "fieldset과 보이는 legend로 그룹 목적을 알리고 native radio를 유지합니다.", en: "Name the native radio set with a fieldset and visible legend." },
    sourcePath: "components/ui/radio-group.tsx",
    demoKey: "radio-group",
    importExample: 'import { RadioGroup } from "@/components/ui/radio-group"',
    usageExample: '<RadioGroup legend="Language" name="locale" options={options} />',
    relatedComponents: ["checkbox", "native-select"],
    dependencies: [],
    states: [
      { id: "default", guidance: { ko: "legend와 모든 선택지 이름을 확인합니다.", en: "Inspect the legend and every option name." } },
      { id: "selected", guidance: { ko: "한 번에 하나만 선택되는지 확인합니다.", en: "Confirm only one option is selected at a time." } },
      { id: "controlled", guidance: { ko: "외부 value와 변경 콜백이 일치하는지 확인합니다.", en: "Confirm external value and change callback stay aligned." } },
      { id: "disabled", guidance: { ko: "개별 선택지와 전체 그룹 비활성 상태를 확인합니다.", en: "Inspect per-option and whole-group disabled states." } },
    ],
    props: [
      { name: "legend", type: "ReactNode", required: true, description: { ko: "선택지 그룹의 보이는 이름입니다.", en: "The visible name of the option group." } },
      { name: "name", type: "string", required: true, description: { ko: "모든 radio가 공유하는 폼 이름입니다.", en: "The form name shared by all radio inputs." } },
      { name: "options", type: "readonly RadioOption[]", required: true, description: { ko: "값, 이름, 설명, 비활성 상태를 담은 선택지입니다.", en: "Options containing value, label, description, and disabled state." } },
      { name: "onValueChange", type: "(value: string) => void", required: false, description: { ko: "선택값이 바뀔 때 호출합니다.", en: "Called when the selected value changes." } },
    ],
  },
  {
    id: "switch",
    name: "Switch",
    category: "selection",
    maturity: "candidate",
    summary: { ko: "즉시 적용되는 하나의 설정을 켜고 끕니다.", en: "Turns one immediately applied setting on or off." },
    whenToUse: { ko: "변경 즉시 효력이 생기는 이진 설정에 씁니다.", en: "Use it for a binary setting that takes effect immediately." },
    whenNotToUse: { ko: "폼 제출 전까지 확정되지 않는 동의에는 Checkbox를 씁니다.", en: "Use Checkbox when consent is only committed on form submission." },
    accessibility: { ko: "native checkbox 동작을 유지하고 role switch와 고정된 이름을 제공합니다.", en: "Preserve native checkbox behavior with role switch and a stable label." },
    sourcePath: "components/ui/switch.tsx",
    demoKey: "switch",
    importExample: 'import { Switch } from "@/components/ui/switch"',
    usageExample: '<Switch label="Allow analytics" />',
    relatedComponents: ["checkbox", "segmented-toggle"],
    dependencies: [],
    states: [
      { id: "off", guidance: { ko: "꺼짐 상태에서도 설정 이름이 분명한지 확인합니다.", en: "Confirm the setting remains clear while off." } },
      { id: "on", guidance: { ko: "thumb 위치와 native checked 상태가 함께 바뀌는지 확인합니다.", en: "Confirm thumb position and native checked state change together." } },
      { id: "focus-visible", guidance: { ko: "트랙 바깥의 키보드 초점선을 확인합니다.", en: "Inspect the keyboard focus outline around the track." } },
      { id: "disabled", guidance: { ko: "현재 값은 보이지만 바꿀 수 없는지 확인합니다.", en: "Confirm the current value stays visible but cannot change." } },
    ],
    props: [
      { name: "label", type: "ReactNode", required: true, description: { ko: "설정의 의미를 설명하는 고정된 이름입니다.", en: "A stable visible name for the setting." } },
      { name: "description", type: "ReactNode", required: false, description: { ko: "설정 효과를 설명하는 보조 문구입니다.", en: "Supporting copy that explains the setting effect." } },
      { name: "checked", type: "boolean", required: false, description: { ko: "제어 모드의 현재 상태입니다.", en: "The current state in controlled mode." } },
      { name: "defaultChecked", type: "boolean", required: false, description: { ko: "비제어 모드의 초기 상태입니다.", en: "The initial state in uncontrolled mode." } },
    ],
  },
] as const satisfies readonly ComponentEntry[]
