export const designComponentSlugs = [
  "logo",
  "action",
  "button",
  "button-group",
  "field",
  "label",
  "input",
  "textarea",
  "native-select",
  "select",
  "checkbox",
  "radio-group",
  "switch",
  "segmented-toggle",
  "icon-control",
  "text-link",
  "dropdown-menu",
  "tabs",
  "accordion",
  "dialog",
  "tooltip",
  "alert-dialog",
  "popover",
  "side-panel",
  "combobox",
  "input-group",
  "breadcrumb",
  "table",
  "data-table",
  "pagination",
  "item",
  "spinner",
  "progress",
  "notice-toast",
  "alert",
  "skeleton",
  "empty-state",
  "separator",
  "panel",
  "status-label",
  "code-block",
] as const

export type DesignComponentSlug = (typeof designComponentSlugs)[number]
