import { execFileSync, spawnSync } from "node:child_process"
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"

import { strFromU8, unzipSync } from "fflate"
import { afterEach, describe, expect, it, vi } from "vitest"

import {
  serializeDesignGuide,
  serializeRootDesign,
  serializeSkillFiles,
  serializeSkillZip,
  serializeTokens,
  strongEtag,
} from "@/lib/design-system/serialize"

const skillPaths = [
  "laflabs-web-design/SKILL.md",
  "laflabs-web-design/references/foundations.md",
  "laflabs-web-design/references/components.md",
  "laflabs-web-design/references/patterns.md",
  "laflabs-web-design/references/tokens.json",
]

function centralDirectoryModes(archive: Uint8Array): ReadonlyMap<string, number> {
  const view = new DataView(archive.buffer, archive.byteOffset, archive.byteLength)
  const decoder = new TextDecoder()
  const modes = new Map<string, number>()

  for (let offset = 0; offset <= archive.byteLength - 46; offset += 1) {
    if (view.getUint32(offset, true) !== 0x02014b50) continue

    const nameLength = view.getUint16(offset + 28, true)
    const extraLength = view.getUint16(offset + 30, true)
    const commentLength = view.getUint16(offset + 32, true)
    const nameStart = offset + 46
    const name = decoder.decode(archive.subarray(nameStart, nameStart + nameLength))
    const externalAttributes = view.getUint32(offset + 38, true)

    modes.set(name, externalAttributes >>> 16)
    offset = nameStart + nameLength + extraLength + commentLength - 1
  }

  return modes
}

function expectOneFinalNewline(source: string): void {
  expect(source.endsWith("\n")).toBe(true)
  expect(source.endsWith("\n\n")).toBe(false)
}

afterEach(() => {
  vi.useRealTimers()
})

describe("design-system serializers", () => {
  it("serializes a provider-neutral guide from the current catalog", () => {
    const guide = serializeDesignGuide()

    expect(guide).toContain("# LafLabs Web Design")
    expect(guide).toContain("System version: 2026.9.0")
    expect(guide).toContain("min(1280px, calc(100% - 64px))")
    expect(guide).toContain("## Components")
    expect(guide).toContain("https://laflabs.co/design/tokens.json")
    expect(guide).not.toContain("calc(100% - 56px)")
    expectOneFinalNewline(guide)
    expect(guide).toBe(serializeDesignGuide())
  })

  it("serializes stable, versioned JSON with tokens sorted by id", () => {
    const source = serializeTokens()
    const document = JSON.parse(source) as {
      name: string
      version: string
      tokens: Array<{ id: string; value: string }>
    }

    expect(document.name).toBe("LafLabs Web Design")
    expect(document.version).toBe("2026.9.0")
    expect(document.tokens.map(({ id }) => id)).toEqual(
      [...document.tokens.map(({ id }) => id)].sort(),
    )
    expect(document.tokens.find(({ id }) => id === "layout.shell")?.value).toBe(
      "min(1280px, calc(100% - 64px))",
    )
    expectOneFinalNewline(source)
    expect(source).toBe(serializeTokens())
  })

  it("builds the exact progressive-disclosure Skill file map", () => {
    const files = serializeSkillFiles()
    const entry = files.get("laflabs-web-design/SKILL.md")

    expect([...files.keys()]).toEqual(skillPaths)
    expect(entry).toContain("name: laflabs-web-design")
    expect(entry).toContain("references/foundations.md")
    expect(entry).toContain("references/components.md")
    expect(entry).toContain("references/patterns.md")
    expect(entry).not.toContain("components/ui/")
    expect(entry).not.toContain("node_modules")
    for (const source of files.values()) expectOneFinalNewline(source)
  })

  it("creates a deterministic, normalized, non-executable Skill zip", () => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date("2026-09-16T00:00:00.000Z"))
    const first = serializeSkillZip()
    vi.setSystemTime(new Date("2027-02-20T14:45:12.000Z"))
    const second = serializeSkillZip()
    const entries = unzipSync(first)

    expect(first).toEqual(second)
    expect(Object.keys(entries)).toEqual(skillPaths)
    expect(Object.keys(entries).every((path) => !path.includes("\\"))).toBe(true)
    expect(Object.keys(entries).every((path) => /\.(?:md|json)$/.test(path))).toBe(true)

    const skillFiles = serializeSkillFiles()
    for (const [path, bytes] of Object.entries(entries)) {
      expect(strFromU8(bytes)).toBe(skillFiles.get(path))
    }

    const modes = centralDirectoryModes(first)
    expect([...modes.keys()]).toEqual(skillPaths)
    expect([...modes.values()].every((mode) => (mode & 0o111) === 0)).toBe(true)
  })

  it("serializes the generated repository guide with public machine resources", () => {
    const source = serializeRootDesign()

    expect(source).toMatch(/^<!-- This file is generated by npm run design:generate\./)
    expect(source).toContain("System version: 2026.9.0")
    expect(source).toContain("## Core principles")
    expect(source).toContain("## Design tokens")
    expect(source).toContain("## Components")
    expect(source).toContain("## Public machine resources")
    expect(source).toContain("https://laflabs.co/design/skill.zip")
    expectOneFinalNewline(source)
    expect(source).toBe(serializeRootDesign())
  })

  it("creates a quoted SHA-256 ETag with Web Crypto", async () => {
    const bytes = new TextEncoder().encode("laflabs")

    await expect(strongEtag(bytes)).resolves.toBe(
      '"a32adaac1bb5701d1215830a671d566e03cf4390151c9be02be724931b8896ef"',
    )
  })
})

describe("design artifact generation", () => {
  it("writes DESIGN.md and detects drift without changing the stale file", () => {
    const temporaryRoot = mkdtempSync(join(tmpdir(), "laflabs-design-system-"))
    const repositoryRoot = process.cwd()
    const script = resolve(repositoryRoot, "scripts/generate-design-system.ts")
    const tsx = resolve(repositoryRoot, "node_modules/.bin/tsx")
    const designPath = join(temporaryRoot, "DESIGN.md")

    try {
      execFileSync(tsx, [script], { cwd: temporaryRoot, encoding: "utf8" })
      expect(readFileSync(designPath, "utf8")).toBe(serializeRootDesign())

      const current = spawnSync(tsx, [script, "--check"], {
        cwd: temporaryRoot,
        encoding: "utf8",
      })
      expect(current.status).toBe(0)

      writeFileSync(designPath, "stale\n", "utf8")
      const stale = spawnSync(tsx, [script, "--check"], {
        cwd: temporaryRoot,
        encoding: "utf8",
      })

      expect(stale.status).toBe(1)
      expect(stale.stderr).toContain("Run npm run design:generate")
      expect(readFileSync(designPath, "utf8")).toBe("stale\n")

      const unsupported = spawnSync(tsx, [script, "--write"], {
        cwd: temporaryRoot,
        encoding: "utf8",
      })
      expect(unsupported.status).toBe(1)
      expect(unsupported.stderr).toContain("Usage: npm run design:generate -- [--check]")
      expect(readFileSync(designPath, "utf8")).toBe("stale\n")
    } finally {
      rmSync(temporaryRoot, { recursive: true, force: true })
    }
  })
})
